// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wifi_config.proto

package com.ash93.esp32_ble_provisioning.ESPProvision.espressif;

public final class WifiConfig {
  private WifiConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code WiFiConfigMsgType}
   */
  public enum WiFiConfigMsgType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>TypeCmdGetStatus = 0;</code>
     */
    TypeCmdGetStatus(0),
    /**
     * <code>TypeRespGetStatus = 1;</code>
     */
    TypeRespGetStatus(1),
    /**
     * <code>TypeCmdSetConfig = 2;</code>
     */
    TypeCmdSetConfig(2),
    /**
     * <code>TypeRespSetConfig = 3;</code>
     */
    TypeRespSetConfig(3),
    /**
     * <code>TypeCmdApplyConfig = 4;</code>
     */
    TypeCmdApplyConfig(4),
    /**
     * <code>TypeRespApplyConfig = 5;</code>
     */
    TypeRespApplyConfig(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TypeCmdGetStatus = 0;</code>
     */
    public static final int TypeCmdGetStatus_VALUE = 0;
    /**
     * <code>TypeRespGetStatus = 1;</code>
     */
    public static final int TypeRespGetStatus_VALUE = 1;
    /**
     * <code>TypeCmdSetConfig = 2;</code>
     */
    public static final int TypeCmdSetConfig_VALUE = 2;
    /**
     * <code>TypeRespSetConfig = 3;</code>
     */
    public static final int TypeRespSetConfig_VALUE = 3;
    /**
     * <code>TypeCmdApplyConfig = 4;</code>
     */
    public static final int TypeCmdApplyConfig_VALUE = 4;
    /**
     * <code>TypeRespApplyConfig = 5;</code>
     */
    public static final int TypeRespApplyConfig_VALUE = 5;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static WiFiConfigMsgType valueOf(int value) {
      return forNumber(value);
    }

    public static WiFiConfigMsgType forNumber(int value) {
      switch (value) {
        case 0: return TypeCmdGetStatus;
        case 1: return TypeRespGetStatus;
        case 2: return TypeCmdSetConfig;
        case 3: return TypeRespSetConfig;
        case 4: return TypeCmdApplyConfig;
        case 5: return TypeRespApplyConfig;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WiFiConfigMsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        WiFiConfigMsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WiFiConfigMsgType>() {
            @Override
            public WiFiConfigMsgType findValueByNumber(int number) {
              return WiFiConfigMsgType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return WiFiConfigMsgTypeVerifier.INSTANCE;
    }

    private static final class WiFiConfigMsgTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new WiFiConfigMsgTypeVerifier();
            @Override
            public boolean isInRange(int number) {
              return WiFiConfigMsgType.forNumber(number) != null;
            }
          };

    private final int value;

    private WiFiConfigMsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WiFiConfigMsgType)
  }

  public interface CmdGetStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CmdGetStatus)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code CmdGetStatus}
   */
  public  static final class CmdGetStatus extends
      com.google.protobuf.GeneratedMessageLite<
          CmdGetStatus, CmdGetStatus.Builder> implements
      // @@protoc_insertion_point(message_implements:CmdGetStatus)
      CmdGetStatusOrBuilder {
    private CmdGetStatus() {
    }
    public static CmdGetStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CmdGetStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CmdGetStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CmdGetStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CmdGetStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CmdGetStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CmdGetStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CmdGetStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CmdGetStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static CmdGetStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CmdGetStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CmdGetStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(CmdGetStatus prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code CmdGetStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          CmdGetStatus, Builder> implements
        // @@protoc_insertion_point(builder_implements:CmdGetStatus)
        CmdGetStatusOrBuilder {
      // Construct using WifiConfig.CmdGetStatus.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:CmdGetStatus)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new CmdGetStatus();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = null;
            String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<CmdGetStatus> parser = PARSER;
          if (parser == null) {
            synchronized (CmdGetStatus.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:CmdGetStatus)
    private static final CmdGetStatus DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new CmdGetStatus();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CmdGetStatus.class, DEFAULT_INSTANCE);
    }
    public static CmdGetStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CmdGetStatus> PARSER;

    public static com.google.protobuf.Parser<CmdGetStatus> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RespGetStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RespGetStatus)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.Status status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.Status status = 1;</code>
     */
    Constants.Status getStatus();

    /**
     * <code>.WifiStationState sta_state = 2;</code>
     */
    int getStaStateValue();
    /**
     * <code>.WifiStationState sta_state = 2;</code>
     */
    WifiConstants.WifiStationState getStaState();

    /**
     * <code>.WifiConnectFailedReason fail_reason = 10;</code>
     */
    int getFailReasonValue();
    /**
     * <code>.WifiConnectFailedReason fail_reason = 10;</code>
     */
    WifiConstants.WifiConnectFailedReason getFailReason();

    /**
     * <code>.WifiConnectedState connected = 11;</code>
     */
    boolean hasConnected();
    /**
     * <code>.WifiConnectedState connected = 11;</code>
     */
    WifiConstants.WifiConnectedState getConnected();

    public RespGetStatus.StateCase getStateCase();
  }
  /**
   * Protobuf type {@code RespGetStatus}
   */
  public  static final class RespGetStatus extends
      com.google.protobuf.GeneratedMessageLite<
          RespGetStatus, RespGetStatus.Builder> implements
      // @@protoc_insertion_point(message_implements:RespGetStatus)
      RespGetStatusOrBuilder {
    private RespGetStatus() {
    }
    private int stateCase_ = 0;
    private Object state_;
    public enum StateCase
        implements com.google.protobuf.Internal.EnumLite {
      FAIL_REASON(10),
      CONNECTED(11),
      STATE_NOT_SET(0);
      private final int value;
      private StateCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static StateCase valueOf(int value) {
        return forNumber(value);
      }

      public static StateCase forNumber(int value) {
        switch (value) {
          case 10: return FAIL_REASON;
          case 11: return CONNECTED;
          case 0: return STATE_NOT_SET;
          default: return null;
        }
      }
      @Override
      public int getNumber() {
        return this.value;
      }
    };

    @Override
    public StateCase
    getStateCase() {
      return StateCase.forNumber(
          stateCase_);
    }

    private void clearState() {
      stateCase_ = 0;
      state_ = null;
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.Status status = 1;</code>
     */
    @Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    @Override
    public Constants.Status getStatus() {
      Constants.Status result = Constants.Status.forNumber(status_);
      return result == null ? Constants.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void setStatus(Constants.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public static final int STA_STATE_FIELD_NUMBER = 2;
    private int staState_;
    /**
     * <code>.WifiStationState sta_state = 2;</code>
     */
    @Override
    public int getStaStateValue() {
      return staState_;
    }
    /**
     * <code>.WifiStationState sta_state = 2;</code>
     */
    @Override
    public WifiConstants.WifiStationState getStaState() {
      WifiConstants.WifiStationState result = WifiConstants.WifiStationState.forNumber(staState_);
      return result == null ? WifiConstants.WifiStationState.UNRECOGNIZED : result;
    }
    /**
     * <code>.WifiStationState sta_state = 2;</code>
     */
    private void setStaStateValue(int value) {
        staState_ = value;
    }
    /**
     * <code>.WifiStationState sta_state = 2;</code>
     */
    private void setStaState(WifiConstants.WifiStationState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      staState_ = value.getNumber();
    }
    /**
     * <code>.WifiStationState sta_state = 2;</code>
     */
    private void clearStaState() {
      
      staState_ = 0;
    }

    public static final int FAIL_REASON_FIELD_NUMBER = 10;
    /**
     * <code>.WifiConnectFailedReason fail_reason = 10;</code>
     */
    @Override
    public int getFailReasonValue() {
      if (stateCase_ == 10) {
        return (Integer) state_;
      }
      return 0;
    }
    /**
     * <code>.WifiConnectFailedReason fail_reason = 10;</code>
     */
    @Override
    public WifiConstants.WifiConnectFailedReason getFailReason() {
      if (stateCase_ == 10) {
        WifiConstants.WifiConnectFailedReason result = WifiConstants.WifiConnectFailedReason.forNumber((Integer) state_);
        return result == null ? WifiConstants.WifiConnectFailedReason.UNRECOGNIZED : result;
      }
      return WifiConstants.WifiConnectFailedReason.AuthError;
    }
    /**
     * <code>.WifiConnectFailedReason fail_reason = 10;</code>
     */
    private void setFailReasonValue(int value) {
      stateCase_ = 10;
      state_ = value;
    }
    /**
     * <code>.WifiConnectFailedReason fail_reason = 10;</code>
     */
    private void setFailReason(WifiConstants.WifiConnectFailedReason value) {
      if (value == null) {
        throw new NullPointerException();
      }
      stateCase_ = 10;
      state_ = value.getNumber();
    }
    /**
     * <code>.WifiConnectFailedReason fail_reason = 10;</code>
     */
    private void clearFailReason() {
      if (stateCase_ == 10) {
        stateCase_ = 0;
        state_ = null;
      }
    }

    public static final int CONNECTED_FIELD_NUMBER = 11;
    /**
     * <code>.WifiConnectedState connected = 11;</code>
     */
    @Override
    public boolean hasConnected() {
      return stateCase_ == 11;
    }
    /**
     * <code>.WifiConnectedState connected = 11;</code>
     */
    @Override
    public WifiConstants.WifiConnectedState getConnected() {
      if (stateCase_ == 11) {
         return (WifiConstants.WifiConnectedState) state_;
      }
      return WifiConstants.WifiConnectedState.getDefaultInstance();
    }
    /**
     * <code>.WifiConnectedState connected = 11;</code>
     */
    private void setConnected(WifiConstants.WifiConnectedState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      state_ = value;
      stateCase_ = 11;
    }
    /**
     * <code>.WifiConnectedState connected = 11;</code>
     */
    private void setConnected(
        WifiConstants.WifiConnectedState.Builder builderForValue) {
      state_ = builderForValue.build();
      stateCase_ = 11;
    }
    /**
     * <code>.WifiConnectedState connected = 11;</code>
     */
    private void mergeConnected(WifiConstants.WifiConnectedState value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (stateCase_ == 11 &&
          state_ != WifiConstants.WifiConnectedState.getDefaultInstance()) {
        state_ = WifiConstants.WifiConnectedState.newBuilder((WifiConstants.WifiConnectedState) state_)
            .mergeFrom(value).buildPartial();
      } else {
        state_ = value;
      }
      stateCase_ = 11;
    }
    /**
     * <code>.WifiConnectedState connected = 11;</code>
     */
    private void clearConnected() {
      if (stateCase_ == 11) {
        stateCase_ = 0;
        state_ = null;
      }
    }

    public static RespGetStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespGetStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespGetStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespGetStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespGetStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespGetStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespGetStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RespGetStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RespGetStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static RespGetStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RespGetStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RespGetStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(RespGetStatus prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code RespGetStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          RespGetStatus, Builder> implements
        // @@protoc_insertion_point(builder_implements:RespGetStatus)
        RespGetStatusOrBuilder {
      // Construct using WifiConfig.RespGetStatus.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @Override
      public StateCase
          getStateCase() {
        return instance.getStateCase();
      }

      public Builder clearState() {
        copyOnWrite();
        instance.clearState();
        return this;
      }


      /**
       * <code>.Status status = 1;</code>
       */
      @Override
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>.Status status = 1;</code>
       */
      @Override
      public Constants.Status getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder setStatus(Constants.Status value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>.WifiStationState sta_state = 2;</code>
       */
      @Override
      public int getStaStateValue() {
        return instance.getStaStateValue();
      }
      /**
       * <code>.WifiStationState sta_state = 2;</code>
       */
      public Builder setStaStateValue(int value) {
        copyOnWrite();
        instance.setStaStateValue(value);
        return this;
      }
      /**
       * <code>.WifiStationState sta_state = 2;</code>
       */
      @Override
      public WifiConstants.WifiStationState getStaState() {
        return instance.getStaState();
      }
      /**
       * <code>.WifiStationState sta_state = 2;</code>
       */
      public Builder setStaState(WifiConstants.WifiStationState value) {
        copyOnWrite();
        instance.setStaState(value);
        return this;
      }
      /**
       * <code>.WifiStationState sta_state = 2;</code>
       */
      public Builder clearStaState() {
        copyOnWrite();
        instance.clearStaState();
        return this;
      }

      /**
       * <code>.WifiConnectFailedReason fail_reason = 10;</code>
       */
      @Override
      public int getFailReasonValue() {
        return instance.getFailReasonValue();
      }
      /**
       * <code>.WifiConnectFailedReason fail_reason = 10;</code>
       */
      public Builder setFailReasonValue(int value) {
        copyOnWrite();
        instance.setFailReasonValue(value);
        return this;
      }
      /**
       * <code>.WifiConnectFailedReason fail_reason = 10;</code>
       */
      @Override
      public WifiConstants.WifiConnectFailedReason getFailReason() {
        return instance.getFailReason();
      }
      /**
       * <code>.WifiConnectFailedReason fail_reason = 10;</code>
       */
      public Builder setFailReason(WifiConstants.WifiConnectFailedReason value) {
        copyOnWrite();
        instance.setFailReason(value);
        return this;
      }
      /**
       * <code>.WifiConnectFailedReason fail_reason = 10;</code>
       */
      public Builder clearFailReason() {
        copyOnWrite();
        instance.clearFailReason();
        return this;
      }

      /**
       * <code>.WifiConnectedState connected = 11;</code>
       */
      @Override
      public boolean hasConnected() {
        return instance.hasConnected();
      }
      /**
       * <code>.WifiConnectedState connected = 11;</code>
       */
      @Override
      public WifiConstants.WifiConnectedState getConnected() {
        return instance.getConnected();
      }
      /**
       * <code>.WifiConnectedState connected = 11;</code>
       */
      public Builder setConnected(WifiConstants.WifiConnectedState value) {
        copyOnWrite();
        instance.setConnected(value);
        return this;
      }
      /**
       * <code>.WifiConnectedState connected = 11;</code>
       */
      public Builder setConnected(
          WifiConstants.WifiConnectedState.Builder builderForValue) {
        copyOnWrite();
        instance.setConnected(builderForValue);
        return this;
      }
      /**
       * <code>.WifiConnectedState connected = 11;</code>
       */
      public Builder mergeConnected(WifiConstants.WifiConnectedState value) {
        copyOnWrite();
        instance.mergeConnected(value);
        return this;
      }
      /**
       * <code>.WifiConnectedState connected = 11;</code>
       */
      public Builder clearConnected() {
        copyOnWrite();
        instance.clearConnected();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RespGetStatus)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new RespGetStatus();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "state_",
              "stateCase_",
              "status_",
              "staState_",
              WifiConstants.WifiConnectedState.class,
            };
            String info =
                "\u0000\u0004\u0001\u0000\u0001\u000b\u0004\u0000\u0000\u0000\u0001\f\u0002\f\n?\u0000" +
                "\u000b<\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<RespGetStatus> parser = PARSER;
          if (parser == null) {
            synchronized (RespGetStatus.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:RespGetStatus)
    private static final RespGetStatus DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new RespGetStatus();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RespGetStatus.class, DEFAULT_INSTANCE);
    }
    public static RespGetStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RespGetStatus> PARSER;

    public static com.google.protobuf.Parser<RespGetStatus> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CmdSetConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CmdSetConfig)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bytes ssid = 1;</code>
     */
    com.google.protobuf.ByteString getSsid();

    /**
     * <code>bytes passphrase = 2;</code>
     */
    com.google.protobuf.ByteString getPassphrase();

    /**
     * <code>bytes bssid = 3;</code>
     */
    com.google.protobuf.ByteString getBssid();

    /**
     * <code>int32 channel = 4;</code>
     */
    int getChannel();
  }
  /**
   * Protobuf type {@code CmdSetConfig}
   */
  public  static final class CmdSetConfig extends
      com.google.protobuf.GeneratedMessageLite<
          CmdSetConfig, CmdSetConfig.Builder> implements
      // @@protoc_insertion_point(message_implements:CmdSetConfig)
      CmdSetConfigOrBuilder {
    private CmdSetConfig() {
      ssid_ = com.google.protobuf.ByteString.EMPTY;
      passphrase_ = com.google.protobuf.ByteString.EMPTY;
      bssid_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int SSID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString ssid_;
    /**
     * <code>bytes ssid = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString getSsid() {
      return ssid_;
    }
    /**
     * <code>bytes ssid = 1;</code>
     */
    private void setSsid(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ssid_ = value;
    }
    /**
     * <code>bytes ssid = 1;</code>
     */
    private void clearSsid() {
      
      ssid_ = getDefaultInstance().getSsid();
    }

    public static final int PASSPHRASE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString passphrase_;
    /**
     * <code>bytes passphrase = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString getPassphrase() {
      return passphrase_;
    }
    /**
     * <code>bytes passphrase = 2;</code>
     */
    private void setPassphrase(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      passphrase_ = value;
    }
    /**
     * <code>bytes passphrase = 2;</code>
     */
    private void clearPassphrase() {
      
      passphrase_ = getDefaultInstance().getPassphrase();
    }

    public static final int BSSID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString bssid_;
    /**
     * <code>bytes bssid = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString getBssid() {
      return bssid_;
    }
    /**
     * <code>bytes bssid = 3;</code>
     */
    private void setBssid(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bssid_ = value;
    }
    /**
     * <code>bytes bssid = 3;</code>
     */
    private void clearBssid() {
      
      bssid_ = getDefaultInstance().getBssid();
    }

    public static final int CHANNEL_FIELD_NUMBER = 4;
    private int channel_;
    /**
     * <code>int32 channel = 4;</code>
     */
    @Override
    public int getChannel() {
      return channel_;
    }
    /**
     * <code>int32 channel = 4;</code>
     */
    private void setChannel(int value) {
      
      channel_ = value;
    }
    /**
     * <code>int32 channel = 4;</code>
     */
    private void clearChannel() {
      
      channel_ = 0;
    }

    public static CmdSetConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CmdSetConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CmdSetConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CmdSetConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CmdSetConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CmdSetConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CmdSetConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CmdSetConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CmdSetConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static CmdSetConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CmdSetConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CmdSetConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(CmdSetConfig prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code CmdSetConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          CmdSetConfig, Builder> implements
        // @@protoc_insertion_point(builder_implements:CmdSetConfig)
        CmdSetConfigOrBuilder {
      // Construct using WifiConfig.CmdSetConfig.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bytes ssid = 1;</code>
       */
      @Override
      public com.google.protobuf.ByteString getSsid() {
        return instance.getSsid();
      }
      /**
       * <code>bytes ssid = 1;</code>
       */
      public Builder setSsid(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSsid(value);
        return this;
      }
      /**
       * <code>bytes ssid = 1;</code>
       */
      public Builder clearSsid() {
        copyOnWrite();
        instance.clearSsid();
        return this;
      }

      /**
       * <code>bytes passphrase = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString getPassphrase() {
        return instance.getPassphrase();
      }
      /**
       * <code>bytes passphrase = 2;</code>
       */
      public Builder setPassphrase(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPassphrase(value);
        return this;
      }
      /**
       * <code>bytes passphrase = 2;</code>
       */
      public Builder clearPassphrase() {
        copyOnWrite();
        instance.clearPassphrase();
        return this;
      }

      /**
       * <code>bytes bssid = 3;</code>
       */
      @Override
      public com.google.protobuf.ByteString getBssid() {
        return instance.getBssid();
      }
      /**
       * <code>bytes bssid = 3;</code>
       */
      public Builder setBssid(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBssid(value);
        return this;
      }
      /**
       * <code>bytes bssid = 3;</code>
       */
      public Builder clearBssid() {
        copyOnWrite();
        instance.clearBssid();
        return this;
      }

      /**
       * <code>int32 channel = 4;</code>
       */
      @Override
      public int getChannel() {
        return instance.getChannel();
      }
      /**
       * <code>int32 channel = 4;</code>
       */
      public Builder setChannel(int value) {
        copyOnWrite();
        instance.setChannel(value);
        return this;
      }
      /**
       * <code>int32 channel = 4;</code>
       */
      public Builder clearChannel() {
        copyOnWrite();
        instance.clearChannel();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CmdSetConfig)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new CmdSetConfig();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "ssid_",
              "passphrase_",
              "bssid_",
              "channel_",
            };
            String info =
                "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\n\u0002\n\u0003" +
                "\n\u0004\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<CmdSetConfig> parser = PARSER;
          if (parser == null) {
            synchronized (CmdSetConfig.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:CmdSetConfig)
    private static final CmdSetConfig DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new CmdSetConfig();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CmdSetConfig.class, DEFAULT_INSTANCE);
    }
    public static CmdSetConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CmdSetConfig> PARSER;

    public static com.google.protobuf.Parser<CmdSetConfig> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RespSetConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RespSetConfig)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.Status status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.Status status = 1;</code>
     */
    Constants.Status getStatus();
  }
  /**
   * Protobuf type {@code RespSetConfig}
   */
  public  static final class RespSetConfig extends
      com.google.protobuf.GeneratedMessageLite<
          RespSetConfig, RespSetConfig.Builder> implements
      // @@protoc_insertion_point(message_implements:RespSetConfig)
      RespSetConfigOrBuilder {
    private RespSetConfig() {
    }
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.Status status = 1;</code>
     */
    @Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    @Override
    public Constants.Status getStatus() {
      Constants.Status result = Constants.Status.forNumber(status_);
      return result == null ? Constants.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void setStatus(Constants.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public static RespSetConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespSetConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespSetConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespSetConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespSetConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespSetConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespSetConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RespSetConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RespSetConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static RespSetConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RespSetConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RespSetConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(RespSetConfig prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code RespSetConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          RespSetConfig, Builder> implements
        // @@protoc_insertion_point(builder_implements:RespSetConfig)
        RespSetConfigOrBuilder {
      // Construct using WifiConfig.RespSetConfig.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.Status status = 1;</code>
       */
      @Override
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>.Status status = 1;</code>
       */
      @Override
      public Constants.Status getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder setStatus(Constants.Status value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RespSetConfig)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new RespSetConfig();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "status_",
            };
            String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<RespSetConfig> parser = PARSER;
          if (parser == null) {
            synchronized (RespSetConfig.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:RespSetConfig)
    private static final RespSetConfig DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new RespSetConfig();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RespSetConfig.class, DEFAULT_INSTANCE);
    }
    public static RespSetConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RespSetConfig> PARSER;

    public static com.google.protobuf.Parser<RespSetConfig> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CmdApplyConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CmdApplyConfig)
      com.google.protobuf.MessageLiteOrBuilder {
  }
  /**
   * Protobuf type {@code CmdApplyConfig}
   */
  public  static final class CmdApplyConfig extends
      com.google.protobuf.GeneratedMessageLite<
          CmdApplyConfig, CmdApplyConfig.Builder> implements
      // @@protoc_insertion_point(message_implements:CmdApplyConfig)
      CmdApplyConfigOrBuilder {
    private CmdApplyConfig() {
    }
    public static CmdApplyConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CmdApplyConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CmdApplyConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CmdApplyConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CmdApplyConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CmdApplyConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CmdApplyConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CmdApplyConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CmdApplyConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static CmdApplyConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CmdApplyConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CmdApplyConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(CmdApplyConfig prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code CmdApplyConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          CmdApplyConfig, Builder> implements
        // @@protoc_insertion_point(builder_implements:CmdApplyConfig)
        CmdApplyConfigOrBuilder {
      // Construct using WifiConfig.CmdApplyConfig.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      // @@protoc_insertion_point(builder_scope:CmdApplyConfig)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new CmdApplyConfig();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = null;
            String info =
                "\u0000\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<CmdApplyConfig> parser = PARSER;
          if (parser == null) {
            synchronized (CmdApplyConfig.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:CmdApplyConfig)
    private static final CmdApplyConfig DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new CmdApplyConfig();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CmdApplyConfig.class, DEFAULT_INSTANCE);
    }
    public static CmdApplyConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CmdApplyConfig> PARSER;

    public static com.google.protobuf.Parser<CmdApplyConfig> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RespApplyConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:RespApplyConfig)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.Status status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.Status status = 1;</code>
     */
    Constants.Status getStatus();
  }
  /**
   * Protobuf type {@code RespApplyConfig}
   */
  public  static final class RespApplyConfig extends
      com.google.protobuf.GeneratedMessageLite<
          RespApplyConfig, RespApplyConfig.Builder> implements
      // @@protoc_insertion_point(message_implements:RespApplyConfig)
      RespApplyConfigOrBuilder {
    private RespApplyConfig() {
    }
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.Status status = 1;</code>
     */
    @Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    @Override
    public Constants.Status getStatus() {
      Constants.Status result = Constants.Status.forNumber(status_);
      return result == null ? Constants.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void setStatus(Constants.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public static RespApplyConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespApplyConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespApplyConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespApplyConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespApplyConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RespApplyConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RespApplyConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RespApplyConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RespApplyConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static RespApplyConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RespApplyConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RespApplyConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(RespApplyConfig prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code RespApplyConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          RespApplyConfig, Builder> implements
        // @@protoc_insertion_point(builder_implements:RespApplyConfig)
        RespApplyConfigOrBuilder {
      // Construct using WifiConfig.RespApplyConfig.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.Status status = 1;</code>
       */
      @Override
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>.Status status = 1;</code>
       */
      @Override
      public Constants.Status getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder setStatus(Constants.Status value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:RespApplyConfig)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new RespApplyConfig();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "status_",
            };
            String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\f";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<RespApplyConfig> parser = PARSER;
          if (parser == null) {
            synchronized (RespApplyConfig.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:RespApplyConfig)
    private static final RespApplyConfig DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new RespApplyConfig();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RespApplyConfig.class, DEFAULT_INSTANCE);
    }
    public static RespApplyConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RespApplyConfig> PARSER;

    public static com.google.protobuf.Parser<RespApplyConfig> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface WiFiConfigPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WiFiConfigPayload)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.WiFiConfigMsgType msg = 1;</code>
     */
    int getMsgValue();
    /**
     * <code>.WiFiConfigMsgType msg = 1;</code>
     */
    WiFiConfigMsgType getMsg();

    /**
     * <code>.CmdGetStatus cmd_get_status = 10;</code>
     */
    boolean hasCmdGetStatus();
    /**
     * <code>.CmdGetStatus cmd_get_status = 10;</code>
     */
    CmdGetStatus getCmdGetStatus();

    /**
     * <code>.RespGetStatus resp_get_status = 11;</code>
     */
    boolean hasRespGetStatus();
    /**
     * <code>.RespGetStatus resp_get_status = 11;</code>
     */
    RespGetStatus getRespGetStatus();

    /**
     * <code>.CmdSetConfig cmd_set_config = 12;</code>
     */
    boolean hasCmdSetConfig();
    /**
     * <code>.CmdSetConfig cmd_set_config = 12;</code>
     */
    CmdSetConfig getCmdSetConfig();

    /**
     * <code>.RespSetConfig resp_set_config = 13;</code>
     */
    boolean hasRespSetConfig();
    /**
     * <code>.RespSetConfig resp_set_config = 13;</code>
     */
    RespSetConfig getRespSetConfig();

    /**
     * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
     */
    boolean hasCmdApplyConfig();
    /**
     * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
     */
    CmdApplyConfig getCmdApplyConfig();

    /**
     * <code>.RespApplyConfig resp_apply_config = 15;</code>
     */
    boolean hasRespApplyConfig();
    /**
     * <code>.RespApplyConfig resp_apply_config = 15;</code>
     */
    RespApplyConfig getRespApplyConfig();

    public WiFiConfigPayload.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code WiFiConfigPayload}
   */
  public  static final class WiFiConfigPayload extends
      com.google.protobuf.GeneratedMessageLite<
          WiFiConfigPayload, WiFiConfigPayload.Builder> implements
      // @@protoc_insertion_point(message_implements:WiFiConfigPayload)
      WiFiConfigPayloadOrBuilder {
    private WiFiConfigPayload() {
    }
    private int payloadCase_ = 0;
    private Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      CMD_GET_STATUS(10),
      RESP_GET_STATUS(11),
      CMD_SET_CONFIG(12),
      RESP_SET_CONFIG(13),
      CMD_APPLY_CONFIG(14),
      RESP_APPLY_CONFIG(15),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 10: return CMD_GET_STATUS;
          case 11: return RESP_GET_STATUS;
          case 12: return CMD_SET_CONFIG;
          case 13: return RESP_SET_CONFIG;
          case 14: return CMD_APPLY_CONFIG;
          case 15: return RESP_APPLY_CONFIG;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      @Override
      public int getNumber() {
        return this.value;
      }
    };

    @Override
    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    private void clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private int msg_;
    /**
     * <code>.WiFiConfigMsgType msg = 1;</code>
     */
    @Override
    public int getMsgValue() {
      return msg_;
    }
    /**
     * <code>.WiFiConfigMsgType msg = 1;</code>
     */
    @Override
    public WifiConfig.WiFiConfigMsgType getMsg() {
      WiFiConfigMsgType result = WiFiConfigMsgType.forNumber(msg_);
      return result == null ? WiFiConfigMsgType.UNRECOGNIZED : result;
    }
    /**
     * <code>.WiFiConfigMsgType msg = 1;</code>
     */
    private void setMsgValue(int value) {
        msg_ = value;
    }
    /**
     * <code>.WiFiConfigMsgType msg = 1;</code>
     */
    private void setMsg(WiFiConfigMsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      msg_ = value.getNumber();
    }
    /**
     * <code>.WiFiConfigMsgType msg = 1;</code>
     */
    private void clearMsg() {
      
      msg_ = 0;
    }

    public static final int CMD_GET_STATUS_FIELD_NUMBER = 10;
    /**
     * <code>.CmdGetStatus cmd_get_status = 10;</code>
     */
    @Override
    public boolean hasCmdGetStatus() {
      return payloadCase_ == 10;
    }
    /**
     * <code>.CmdGetStatus cmd_get_status = 10;</code>
     */
    @Override
    public WifiConfig.CmdGetStatus getCmdGetStatus() {
      if (payloadCase_ == 10) {
         return (CmdGetStatus) payload_;
      }
      return CmdGetStatus.getDefaultInstance();
    }
    /**
     * <code>.CmdGetStatus cmd_get_status = 10;</code>
     */
    private void setCmdGetStatus(CmdGetStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 10;
    }
    /**
     * <code>.CmdGetStatus cmd_get_status = 10;</code>
     */
    private void setCmdGetStatus(
        CmdGetStatus.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 10;
    }
    /**
     * <code>.CmdGetStatus cmd_get_status = 10;</code>
     */
    private void mergeCmdGetStatus(CmdGetStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 10 &&
          payload_ != CmdGetStatus.getDefaultInstance()) {
        payload_ = CmdGetStatus.newBuilder((CmdGetStatus) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 10;
    }
    /**
     * <code>.CmdGetStatus cmd_get_status = 10;</code>
     */
    private void clearCmdGetStatus() {
      if (payloadCase_ == 10) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static final int RESP_GET_STATUS_FIELD_NUMBER = 11;
    /**
     * <code>.RespGetStatus resp_get_status = 11;</code>
     */
    @Override
    public boolean hasRespGetStatus() {
      return payloadCase_ == 11;
    }
    /**
     * <code>.RespGetStatus resp_get_status = 11;</code>
     */
    @Override
    public WifiConfig.RespGetStatus getRespGetStatus() {
      if (payloadCase_ == 11) {
         return (RespGetStatus) payload_;
      }
      return RespGetStatus.getDefaultInstance();
    }
    /**
     * <code>.RespGetStatus resp_get_status = 11;</code>
     */
    private void setRespGetStatus(RespGetStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 11;
    }
    /**
     * <code>.RespGetStatus resp_get_status = 11;</code>
     */
    private void setRespGetStatus(
        RespGetStatus.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 11;
    }
    /**
     * <code>.RespGetStatus resp_get_status = 11;</code>
     */
    private void mergeRespGetStatus(RespGetStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 11 &&
          payload_ != RespGetStatus.getDefaultInstance()) {
        payload_ = RespGetStatus.newBuilder((RespGetStatus) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 11;
    }
    /**
     * <code>.RespGetStatus resp_get_status = 11;</code>
     */
    private void clearRespGetStatus() {
      if (payloadCase_ == 11) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static final int CMD_SET_CONFIG_FIELD_NUMBER = 12;
    /**
     * <code>.CmdSetConfig cmd_set_config = 12;</code>
     */
    @Override
    public boolean hasCmdSetConfig() {
      return payloadCase_ == 12;
    }
    /**
     * <code>.CmdSetConfig cmd_set_config = 12;</code>
     */
    @Override
    public WifiConfig.CmdSetConfig getCmdSetConfig() {
      if (payloadCase_ == 12) {
         return (CmdSetConfig) payload_;
      }
      return CmdSetConfig.getDefaultInstance();
    }
    /**
     * <code>.CmdSetConfig cmd_set_config = 12;</code>
     */
    private void setCmdSetConfig(CmdSetConfig value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 12;
    }
    /**
     * <code>.CmdSetConfig cmd_set_config = 12;</code>
     */
    private void setCmdSetConfig(
        CmdSetConfig.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 12;
    }
    /**
     * <code>.CmdSetConfig cmd_set_config = 12;</code>
     */
    private void mergeCmdSetConfig(CmdSetConfig value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 12 &&
          payload_ != CmdSetConfig.getDefaultInstance()) {
        payload_ = CmdSetConfig.newBuilder((CmdSetConfig) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 12;
    }
    /**
     * <code>.CmdSetConfig cmd_set_config = 12;</code>
     */
    private void clearCmdSetConfig() {
      if (payloadCase_ == 12) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static final int RESP_SET_CONFIG_FIELD_NUMBER = 13;
    /**
     * <code>.RespSetConfig resp_set_config = 13;</code>
     */
    @Override
    public boolean hasRespSetConfig() {
      return payloadCase_ == 13;
    }
    /**
     * <code>.RespSetConfig resp_set_config = 13;</code>
     */
    @Override
    public WifiConfig.RespSetConfig getRespSetConfig() {
      if (payloadCase_ == 13) {
         return (RespSetConfig) payload_;
      }
      return RespSetConfig.getDefaultInstance();
    }
    /**
     * <code>.RespSetConfig resp_set_config = 13;</code>
     */
    private void setRespSetConfig(RespSetConfig value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 13;
    }
    /**
     * <code>.RespSetConfig resp_set_config = 13;</code>
     */
    private void setRespSetConfig(
        RespSetConfig.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 13;
    }
    /**
     * <code>.RespSetConfig resp_set_config = 13;</code>
     */
    private void mergeRespSetConfig(RespSetConfig value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 13 &&
          payload_ != RespSetConfig.getDefaultInstance()) {
        payload_ = RespSetConfig.newBuilder((RespSetConfig) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 13;
    }
    /**
     * <code>.RespSetConfig resp_set_config = 13;</code>
     */
    private void clearRespSetConfig() {
      if (payloadCase_ == 13) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static final int CMD_APPLY_CONFIG_FIELD_NUMBER = 14;
    /**
     * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
     */
    @Override
    public boolean hasCmdApplyConfig() {
      return payloadCase_ == 14;
    }
    /**
     * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
     */
    @Override
    public WifiConfig.CmdApplyConfig getCmdApplyConfig() {
      if (payloadCase_ == 14) {
         return (CmdApplyConfig) payload_;
      }
      return CmdApplyConfig.getDefaultInstance();
    }
    /**
     * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
     */
    private void setCmdApplyConfig(CmdApplyConfig value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 14;
    }
    /**
     * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
     */
    private void setCmdApplyConfig(
        CmdApplyConfig.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 14;
    }
    /**
     * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
     */
    private void mergeCmdApplyConfig(CmdApplyConfig value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 14 &&
          payload_ != CmdApplyConfig.getDefaultInstance()) {
        payload_ = CmdApplyConfig.newBuilder((CmdApplyConfig) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 14;
    }
    /**
     * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
     */
    private void clearCmdApplyConfig() {
      if (payloadCase_ == 14) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static final int RESP_APPLY_CONFIG_FIELD_NUMBER = 15;
    /**
     * <code>.RespApplyConfig resp_apply_config = 15;</code>
     */
    @Override
    public boolean hasRespApplyConfig() {
      return payloadCase_ == 15;
    }
    /**
     * <code>.RespApplyConfig resp_apply_config = 15;</code>
     */
    @Override
    public WifiConfig.RespApplyConfig getRespApplyConfig() {
      if (payloadCase_ == 15) {
         return (RespApplyConfig) payload_;
      }
      return RespApplyConfig.getDefaultInstance();
    }
    /**
     * <code>.RespApplyConfig resp_apply_config = 15;</code>
     */
    private void setRespApplyConfig(RespApplyConfig value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 15;
    }
    /**
     * <code>.RespApplyConfig resp_apply_config = 15;</code>
     */
    private void setRespApplyConfig(
        RespApplyConfig.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 15;
    }
    /**
     * <code>.RespApplyConfig resp_apply_config = 15;</code>
     */
    private void mergeRespApplyConfig(RespApplyConfig value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 15 &&
          payload_ != RespApplyConfig.getDefaultInstance()) {
        payload_ = RespApplyConfig.newBuilder((RespApplyConfig) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 15;
    }
    /**
     * <code>.RespApplyConfig resp_apply_config = 15;</code>
     */
    private void clearRespApplyConfig() {
      if (payloadCase_ == 15) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static WiFiConfigPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WiFiConfigPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WiFiConfigPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WiFiConfigPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WiFiConfigPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WiFiConfigPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WiFiConfigPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static WiFiConfigPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static WiFiConfigPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static WiFiConfigPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static WiFiConfigPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static WiFiConfigPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(WiFiConfigPayload prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code WiFiConfigPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          WiFiConfigPayload, Builder> implements
        // @@protoc_insertion_point(builder_implements:WiFiConfigPayload)
        WiFiConfigPayloadOrBuilder {
      // Construct using WifiConfig.WiFiConfigPayload.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @Override
      public PayloadCase
          getPayloadCase() {
        return instance.getPayloadCase();
      }

      public Builder clearPayload() {
        copyOnWrite();
        instance.clearPayload();
        return this;
      }


      /**
       * <code>.WiFiConfigMsgType msg = 1;</code>
       */
      @Override
      public int getMsgValue() {
        return instance.getMsgValue();
      }
      /**
       * <code>.WiFiConfigMsgType msg = 1;</code>
       */
      public Builder setMsgValue(int value) {
        copyOnWrite();
        instance.setMsgValue(value);
        return this;
      }
      /**
       * <code>.WiFiConfigMsgType msg = 1;</code>
       */
      @Override
      public WifiConfig.WiFiConfigMsgType getMsg() {
        return instance.getMsg();
      }
      /**
       * <code>.WiFiConfigMsgType msg = 1;</code>
       */
      public Builder setMsg(WiFiConfigMsgType value) {
        copyOnWrite();
        instance.setMsg(value);
        return this;
      }
      /**
       * <code>.WiFiConfigMsgType msg = 1;</code>
       */
      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }

      /**
       * <code>.CmdGetStatus cmd_get_status = 10;</code>
       */
      @Override
      public boolean hasCmdGetStatus() {
        return instance.hasCmdGetStatus();
      }
      /**
       * <code>.CmdGetStatus cmd_get_status = 10;</code>
       */
      @Override
      public WifiConfig.CmdGetStatus getCmdGetStatus() {
        return instance.getCmdGetStatus();
      }
      /**
       * <code>.CmdGetStatus cmd_get_status = 10;</code>
       */
      public Builder setCmdGetStatus(CmdGetStatus value) {
        copyOnWrite();
        instance.setCmdGetStatus(value);
        return this;
      }
      /**
       * <code>.CmdGetStatus cmd_get_status = 10;</code>
       */
      public Builder setCmdGetStatus(
          CmdGetStatus.Builder builderForValue) {
        copyOnWrite();
        instance.setCmdGetStatus(builderForValue);
        return this;
      }
      /**
       * <code>.CmdGetStatus cmd_get_status = 10;</code>
       */
      public Builder mergeCmdGetStatus(CmdGetStatus value) {
        copyOnWrite();
        instance.mergeCmdGetStatus(value);
        return this;
      }
      /**
       * <code>.CmdGetStatus cmd_get_status = 10;</code>
       */
      public Builder clearCmdGetStatus() {
        copyOnWrite();
        instance.clearCmdGetStatus();
        return this;
      }

      /**
       * <code>.RespGetStatus resp_get_status = 11;</code>
       */
      @Override
      public boolean hasRespGetStatus() {
        return instance.hasRespGetStatus();
      }
      /**
       * <code>.RespGetStatus resp_get_status = 11;</code>
       */
      @Override
      public WifiConfig.RespGetStatus getRespGetStatus() {
        return instance.getRespGetStatus();
      }
      /**
       * <code>.RespGetStatus resp_get_status = 11;</code>
       */
      public Builder setRespGetStatus(RespGetStatus value) {
        copyOnWrite();
        instance.setRespGetStatus(value);
        return this;
      }
      /**
       * <code>.RespGetStatus resp_get_status = 11;</code>
       */
      public Builder setRespGetStatus(
          RespGetStatus.Builder builderForValue) {
        copyOnWrite();
        instance.setRespGetStatus(builderForValue);
        return this;
      }
      /**
       * <code>.RespGetStatus resp_get_status = 11;</code>
       */
      public Builder mergeRespGetStatus(RespGetStatus value) {
        copyOnWrite();
        instance.mergeRespGetStatus(value);
        return this;
      }
      /**
       * <code>.RespGetStatus resp_get_status = 11;</code>
       */
      public Builder clearRespGetStatus() {
        copyOnWrite();
        instance.clearRespGetStatus();
        return this;
      }

      /**
       * <code>.CmdSetConfig cmd_set_config = 12;</code>
       */
      @Override
      public boolean hasCmdSetConfig() {
        return instance.hasCmdSetConfig();
      }
      /**
       * <code>.CmdSetConfig cmd_set_config = 12;</code>
       */
      @Override
      public WifiConfig.CmdSetConfig getCmdSetConfig() {
        return instance.getCmdSetConfig();
      }
      /**
       * <code>.CmdSetConfig cmd_set_config = 12;</code>
       */
      public Builder setCmdSetConfig(CmdSetConfig value) {
        copyOnWrite();
        instance.setCmdSetConfig(value);
        return this;
      }
      /**
       * <code>.CmdSetConfig cmd_set_config = 12;</code>
       */
      public Builder setCmdSetConfig(
          CmdSetConfig.Builder builderForValue) {
        copyOnWrite();
        instance.setCmdSetConfig(builderForValue);
        return this;
      }
      /**
       * <code>.CmdSetConfig cmd_set_config = 12;</code>
       */
      public Builder mergeCmdSetConfig(CmdSetConfig value) {
        copyOnWrite();
        instance.mergeCmdSetConfig(value);
        return this;
      }
      /**
       * <code>.CmdSetConfig cmd_set_config = 12;</code>
       */
      public Builder clearCmdSetConfig() {
        copyOnWrite();
        instance.clearCmdSetConfig();
        return this;
      }

      /**
       * <code>.RespSetConfig resp_set_config = 13;</code>
       */
      @Override
      public boolean hasRespSetConfig() {
        return instance.hasRespSetConfig();
      }
      /**
       * <code>.RespSetConfig resp_set_config = 13;</code>
       */
      @Override
      public WifiConfig.RespSetConfig getRespSetConfig() {
        return instance.getRespSetConfig();
      }
      /**
       * <code>.RespSetConfig resp_set_config = 13;</code>
       */
      public Builder setRespSetConfig(RespSetConfig value) {
        copyOnWrite();
        instance.setRespSetConfig(value);
        return this;
      }
      /**
       * <code>.RespSetConfig resp_set_config = 13;</code>
       */
      public Builder setRespSetConfig(
          RespSetConfig.Builder builderForValue) {
        copyOnWrite();
        instance.setRespSetConfig(builderForValue);
        return this;
      }
      /**
       * <code>.RespSetConfig resp_set_config = 13;</code>
       */
      public Builder mergeRespSetConfig(RespSetConfig value) {
        copyOnWrite();
        instance.mergeRespSetConfig(value);
        return this;
      }
      /**
       * <code>.RespSetConfig resp_set_config = 13;</code>
       */
      public Builder clearRespSetConfig() {
        copyOnWrite();
        instance.clearRespSetConfig();
        return this;
      }

      /**
       * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
       */
      @Override
      public boolean hasCmdApplyConfig() {
        return instance.hasCmdApplyConfig();
      }
      /**
       * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
       */
      @Override
      public WifiConfig.CmdApplyConfig getCmdApplyConfig() {
        return instance.getCmdApplyConfig();
      }
      /**
       * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
       */
      public Builder setCmdApplyConfig(CmdApplyConfig value) {
        copyOnWrite();
        instance.setCmdApplyConfig(value);
        return this;
      }
      /**
       * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
       */
      public Builder setCmdApplyConfig(
          CmdApplyConfig.Builder builderForValue) {
        copyOnWrite();
        instance.setCmdApplyConfig(builderForValue);
        return this;
      }
      /**
       * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
       */
      public Builder mergeCmdApplyConfig(CmdApplyConfig value) {
        copyOnWrite();
        instance.mergeCmdApplyConfig(value);
        return this;
      }
      /**
       * <code>.CmdApplyConfig cmd_apply_config = 14;</code>
       */
      public Builder clearCmdApplyConfig() {
        copyOnWrite();
        instance.clearCmdApplyConfig();
        return this;
      }

      /**
       * <code>.RespApplyConfig resp_apply_config = 15;</code>
       */
      @Override
      public boolean hasRespApplyConfig() {
        return instance.hasRespApplyConfig();
      }
      /**
       * <code>.RespApplyConfig resp_apply_config = 15;</code>
       */
      @Override
      public WifiConfig.RespApplyConfig getRespApplyConfig() {
        return instance.getRespApplyConfig();
      }
      /**
       * <code>.RespApplyConfig resp_apply_config = 15;</code>
       */
      public Builder setRespApplyConfig(RespApplyConfig value) {
        copyOnWrite();
        instance.setRespApplyConfig(value);
        return this;
      }
      /**
       * <code>.RespApplyConfig resp_apply_config = 15;</code>
       */
      public Builder setRespApplyConfig(
          RespApplyConfig.Builder builderForValue) {
        copyOnWrite();
        instance.setRespApplyConfig(builderForValue);
        return this;
      }
      /**
       * <code>.RespApplyConfig resp_apply_config = 15;</code>
       */
      public Builder mergeRespApplyConfig(RespApplyConfig value) {
        copyOnWrite();
        instance.mergeRespApplyConfig(value);
        return this;
      }
      /**
       * <code>.RespApplyConfig resp_apply_config = 15;</code>
       */
      public Builder clearRespApplyConfig() {
        copyOnWrite();
        instance.clearRespApplyConfig();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:WiFiConfigPayload)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new WiFiConfigPayload();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "payload_",
              "payloadCase_",
              "msg_",
              CmdGetStatus.class,
              RespGetStatus.class,
              CmdSetConfig.class,
              RespSetConfig.class,
              CmdApplyConfig.class,
              RespApplyConfig.class,
            };
            String info =
                "\u0000\u0007\u0001\u0000\u0001\u000f\u0007\u0000\u0000\u0000\u0001\f\n<\u0000\u000b" +
                "<\u0000\f<\u0000\r<\u0000\u000e<\u0000\u000f<\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<WiFiConfigPayload> parser = PARSER;
          if (parser == null) {
            synchronized (WiFiConfigPayload.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:WiFiConfigPayload)
    private static final WiFiConfigPayload DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new WiFiConfigPayload();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        WiFiConfigPayload.class, DEFAULT_INSTANCE);
    }
    public static WiFiConfigPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<WiFiConfigPayload> PARSER;

    public static com.google.protobuf.Parser<WiFiConfigPayload> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
