// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wifi_constants.proto

package com.ash93.esp32_ble_provisioning.ESPProvision.espressif;

public final class WifiConstants {
  private WifiConstants() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code WifiStationState}
   */
  public enum WifiStationState
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Connected = 0;</code>
     */
    Connected(0),
    /**
     * <code>Connecting = 1;</code>
     */
    Connecting(1),
    /**
     * <code>Disconnected = 2;</code>
     */
    Disconnected(2),
    /**
     * <code>ConnectionFailed = 3;</code>
     */
    ConnectionFailed(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Connected = 0;</code>
     */
    public static final int Connected_VALUE = 0;
    /**
     * <code>Connecting = 1;</code>
     */
    public static final int Connecting_VALUE = 1;
    /**
     * <code>Disconnected = 2;</code>
     */
    public static final int Disconnected_VALUE = 2;
    /**
     * <code>ConnectionFailed = 3;</code>
     */
    public static final int ConnectionFailed_VALUE = 3;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static WifiStationState valueOf(int value) {
      return forNumber(value);
    }

    public static WifiStationState forNumber(int value) {
      switch (value) {
        case 0: return Connected;
        case 1: return Connecting;
        case 2: return Disconnected;
        case 3: return ConnectionFailed;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WifiStationState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        WifiStationState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WifiStationState>() {
            @Override
            public WifiStationState findValueByNumber(int number) {
              return WifiStationState.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return WifiStationStateVerifier.INSTANCE;
    }

    private static final class WifiStationStateVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new WifiStationStateVerifier();
            @Override
            public boolean isInRange(int number) {
              return WifiStationState.forNumber(number) != null;
            }
          };

    private final int value;

    private WifiStationState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WifiStationState)
  }

  /**
   * Protobuf enum {@code WifiConnectFailedReason}
   */
  public enum WifiConnectFailedReason
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>AuthError = 0;</code>
     */
    AuthError(0),
    /**
     * <code>NetworkNotFound = 1;</code>
     */
    NetworkNotFound(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>AuthError = 0;</code>
     */
    public static final int AuthError_VALUE = 0;
    /**
     * <code>NetworkNotFound = 1;</code>
     */
    public static final int NetworkNotFound_VALUE = 1;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static WifiConnectFailedReason valueOf(int value) {
      return forNumber(value);
    }

    public static WifiConnectFailedReason forNumber(int value) {
      switch (value) {
        case 0: return AuthError;
        case 1: return NetworkNotFound;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WifiConnectFailedReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        WifiConnectFailedReason> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WifiConnectFailedReason>() {
            @Override
            public WifiConnectFailedReason findValueByNumber(int number) {
              return WifiConnectFailedReason.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return WifiConnectFailedReasonVerifier.INSTANCE;
    }

    private static final class WifiConnectFailedReasonVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new WifiConnectFailedReasonVerifier();
            @Override
            public boolean isInRange(int number) {
              return WifiConnectFailedReason.forNumber(number) != null;
            }
          };

    private final int value;

    private WifiConnectFailedReason(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WifiConnectFailedReason)
  }

  /**
   * Protobuf enum {@code WifiAuthMode}
   */
  public enum WifiAuthMode
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Open = 0;</code>
     */
    Open(0),
    /**
     * <code>WEP = 1;</code>
     */
    WEP(1),
    /**
     * <code>WPA_PSK = 2;</code>
     */
    WPA_PSK(2),
    /**
     * <code>WPA2_PSK = 3;</code>
     */
    WPA2_PSK(3),
    /**
     * <code>WPA_WPA2_PSK = 4;</code>
     */
    WPA_WPA2_PSK(4),
    /**
     * <code>WPA2_ENTERPRISE = 5;</code>
     */
    WPA2_ENTERPRISE(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Open = 0;</code>
     */
    public static final int Open_VALUE = 0;
    /**
     * <code>WEP = 1;</code>
     */
    public static final int WEP_VALUE = 1;
    /**
     * <code>WPA_PSK = 2;</code>
     */
    public static final int WPA_PSK_VALUE = 2;
    /**
     * <code>WPA2_PSK = 3;</code>
     */
    public static final int WPA2_PSK_VALUE = 3;
    /**
     * <code>WPA_WPA2_PSK = 4;</code>
     */
    public static final int WPA_WPA2_PSK_VALUE = 4;
    /**
     * <code>WPA2_ENTERPRISE = 5;</code>
     */
    public static final int WPA2_ENTERPRISE_VALUE = 5;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static WifiAuthMode valueOf(int value) {
      return forNumber(value);
    }

    public static WifiAuthMode forNumber(int value) {
      switch (value) {
        case 0: return Open;
        case 1: return WEP;
        case 2: return WPA_PSK;
        case 3: return WPA2_PSK;
        case 4: return WPA_WPA2_PSK;
        case 5: return WPA2_ENTERPRISE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WifiAuthMode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        WifiAuthMode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WifiAuthMode>() {
            @Override
            public WifiAuthMode findValueByNumber(int number) {
              return WifiAuthMode.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return WifiAuthModeVerifier.INSTANCE;
    }

    private static final class WifiAuthModeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new WifiAuthModeVerifier();
            @Override
            public boolean isInRange(int number) {
              return WifiAuthMode.forNumber(number) != null;
            }
          };

    private final int value;

    private WifiAuthMode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WifiAuthMode)
  }

  public interface WifiConnectedStateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WifiConnectedState)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string ip4_addr = 1;</code>
     */
    String getIp4Addr();
    /**
     * <code>string ip4_addr = 1;</code>
     */
    com.google.protobuf.ByteString
        getIp4AddrBytes();

    /**
     * <code>.WifiAuthMode auth_mode = 2;</code>
     */
    int getAuthModeValue();
    /**
     * <code>.WifiAuthMode auth_mode = 2;</code>
     */
    WifiAuthMode getAuthMode();

    /**
     * <code>bytes ssid = 3;</code>
     */
    com.google.protobuf.ByteString getSsid();

    /**
     * <code>bytes bssid = 4;</code>
     */
    com.google.protobuf.ByteString getBssid();

    /**
     * <code>int32 channel = 5;</code>
     */
    int getChannel();
  }
  /**
   * Protobuf type {@code WifiConnectedState}
   */
  public  static final class WifiConnectedState extends
      com.google.protobuf.GeneratedMessageLite<
          WifiConnectedState, WifiConnectedState.Builder> implements
      // @@protoc_insertion_point(message_implements:WifiConnectedState)
      WifiConnectedStateOrBuilder {
    private WifiConnectedState() {
      ip4Addr_ = "";
      ssid_ = com.google.protobuf.ByteString.EMPTY;
      bssid_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int IP4_ADDR_FIELD_NUMBER = 1;
    private String ip4Addr_;
    /**
     * <code>string ip4_addr = 1;</code>
     */
    @Override
    public String getIp4Addr() {
      return ip4Addr_;
    }
    /**
     * <code>string ip4_addr = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getIp4AddrBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ip4Addr_);
    }
    /**
     * <code>string ip4_addr = 1;</code>
     */
    private void setIp4Addr(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ip4Addr_ = value;
    }
    /**
     * <code>string ip4_addr = 1;</code>
     */
    private void clearIp4Addr() {
      
      ip4Addr_ = getDefaultInstance().getIp4Addr();
    }
    /**
     * <code>string ip4_addr = 1;</code>
     */
    private void setIp4AddrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ip4Addr_ = value.toStringUtf8();
    }

    public static final int AUTH_MODE_FIELD_NUMBER = 2;
    private int authMode_;
    /**
     * <code>.WifiAuthMode auth_mode = 2;</code>
     */
    @Override
    public int getAuthModeValue() {
      return authMode_;
    }
    /**
     * <code>.WifiAuthMode auth_mode = 2;</code>
     */
    @Override
    public WifiConstants.WifiAuthMode getAuthMode() {
      WifiAuthMode result = WifiAuthMode.forNumber(authMode_);
      return result == null ? WifiAuthMode.UNRECOGNIZED : result;
    }
    /**
     * <code>.WifiAuthMode auth_mode = 2;</code>
     */
    private void setAuthModeValue(int value) {
        authMode_ = value;
    }
    /**
     * <code>.WifiAuthMode auth_mode = 2;</code>
     */
    private void setAuthMode(WifiAuthMode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      authMode_ = value.getNumber();
    }
    /**
     * <code>.WifiAuthMode auth_mode = 2;</code>
     */
    private void clearAuthMode() {
      
      authMode_ = 0;
    }

    public static final int SSID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString ssid_;
    /**
     * <code>bytes ssid = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString getSsid() {
      return ssid_;
    }
    /**
     * <code>bytes ssid = 3;</code>
     */
    private void setSsid(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ssid_ = value;
    }
    /**
     * <code>bytes ssid = 3;</code>
     */
    private void clearSsid() {
      
      ssid_ = getDefaultInstance().getSsid();
    }

    public static final int BSSID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString bssid_;
    /**
     * <code>bytes bssid = 4;</code>
     */
    @Override
    public com.google.protobuf.ByteString getBssid() {
      return bssid_;
    }
    /**
     * <code>bytes bssid = 4;</code>
     */
    private void setBssid(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      bssid_ = value;
    }
    /**
     * <code>bytes bssid = 4;</code>
     */
    private void clearBssid() {
      
      bssid_ = getDefaultInstance().getBssid();
    }

    public static final int CHANNEL_FIELD_NUMBER = 5;
    private int channel_;
    /**
     * <code>int32 channel = 5;</code>
     */
    @Override
    public int getChannel() {
      return channel_;
    }
    /**
     * <code>int32 channel = 5;</code>
     */
    private void setChannel(int value) {
      
      channel_ = value;
    }
    /**
     * <code>int32 channel = 5;</code>
     */
    private void clearChannel() {
      
      channel_ = 0;
    }

    public static WifiConnectedState parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WifiConnectedState parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WifiConnectedState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WifiConnectedState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WifiConnectedState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static WifiConnectedState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static WifiConnectedState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static WifiConnectedState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static WifiConnectedState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static WifiConnectedState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static WifiConnectedState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static WifiConnectedState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(WifiConnectedState prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code WifiConnectedState}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          WifiConnectedState, Builder> implements
        // @@protoc_insertion_point(builder_implements:WifiConnectedState)
        WifiConnectedStateOrBuilder {
      // Construct using WifiConstants.WifiConnectedState.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string ip4_addr = 1;</code>
       */
      @Override
      public String getIp4Addr() {
        return instance.getIp4Addr();
      }
      /**
       * <code>string ip4_addr = 1;</code>
       */
      @Override
      public com.google.protobuf.ByteString
          getIp4AddrBytes() {
        return instance.getIp4AddrBytes();
      }
      /**
       * <code>string ip4_addr = 1;</code>
       */
      public Builder setIp4Addr(
          String value) {
        copyOnWrite();
        instance.setIp4Addr(value);
        return this;
      }
      /**
       * <code>string ip4_addr = 1;</code>
       */
      public Builder clearIp4Addr() {
        copyOnWrite();
        instance.clearIp4Addr();
        return this;
      }
      /**
       * <code>string ip4_addr = 1;</code>
       */
      public Builder setIp4AddrBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIp4AddrBytes(value);
        return this;
      }

      /**
       * <code>.WifiAuthMode auth_mode = 2;</code>
       */
      @Override
      public int getAuthModeValue() {
        return instance.getAuthModeValue();
      }
      /**
       * <code>.WifiAuthMode auth_mode = 2;</code>
       */
      public Builder setAuthModeValue(int value) {
        copyOnWrite();
        instance.setAuthModeValue(value);
        return this;
      }
      /**
       * <code>.WifiAuthMode auth_mode = 2;</code>
       */
      @Override
      public WifiConstants.WifiAuthMode getAuthMode() {
        return instance.getAuthMode();
      }
      /**
       * <code>.WifiAuthMode auth_mode = 2;</code>
       */
      public Builder setAuthMode(WifiAuthMode value) {
        copyOnWrite();
        instance.setAuthMode(value);
        return this;
      }
      /**
       * <code>.WifiAuthMode auth_mode = 2;</code>
       */
      public Builder clearAuthMode() {
        copyOnWrite();
        instance.clearAuthMode();
        return this;
      }

      /**
       * <code>bytes ssid = 3;</code>
       */
      @Override
      public com.google.protobuf.ByteString getSsid() {
        return instance.getSsid();
      }
      /**
       * <code>bytes ssid = 3;</code>
       */
      public Builder setSsid(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSsid(value);
        return this;
      }
      /**
       * <code>bytes ssid = 3;</code>
       */
      public Builder clearSsid() {
        copyOnWrite();
        instance.clearSsid();
        return this;
      }

      /**
       * <code>bytes bssid = 4;</code>
       */
      @Override
      public com.google.protobuf.ByteString getBssid() {
        return instance.getBssid();
      }
      /**
       * <code>bytes bssid = 4;</code>
       */
      public Builder setBssid(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBssid(value);
        return this;
      }
      /**
       * <code>bytes bssid = 4;</code>
       */
      public Builder clearBssid() {
        copyOnWrite();
        instance.clearBssid();
        return this;
      }

      /**
       * <code>int32 channel = 5;</code>
       */
      @Override
      public int getChannel() {
        return instance.getChannel();
      }
      /**
       * <code>int32 channel = 5;</code>
       */
      public Builder setChannel(int value) {
        copyOnWrite();
        instance.setChannel(value);
        return this;
      }
      /**
       * <code>int32 channel = 5;</code>
       */
      public Builder clearChannel() {
        copyOnWrite();
        instance.clearChannel();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:WifiConnectedState)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new WifiConnectedState();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "ip4Addr_",
              "authMode_",
              "ssid_",
              "bssid_",
              "channel_",
            };
            String info =
                "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\f" +
                "\u0003\n\u0004\n\u0005\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<WifiConnectedState> parser = PARSER;
          if (parser == null) {
            synchronized (WifiConnectedState.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:WifiConnectedState)
    private static final WifiConnectedState DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new WifiConnectedState();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        WifiConnectedState.class, DEFAULT_INSTANCE);
    }
    public static WifiConnectedState getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<WifiConnectedState> PARSER;

    public static com.google.protobuf.Parser<WifiConnectedState> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
