// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sec1.proto

package com.ash93.esp32_ble_provisioning_plugin.ESPProvision.espressif;

public final class Sec1 {
  private Sec1() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code Sec1MsgType}
   */
  public enum Sec1MsgType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>Session_Command0 = 0;</code>
     */
    Session_Command0(0),
    /**
     * <code>Session_Response0 = 1;</code>
     */
    Session_Response0(1),
    /**
     * <code>Session_Command1 = 2;</code>
     */
    Session_Command1(2),
    /**
     * <code>Session_Response1 = 3;</code>
     */
    Session_Response1(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>Session_Command0 = 0;</code>
     */
    public static final int Session_Command0_VALUE = 0;
    /**
     * <code>Session_Response0 = 1;</code>
     */
    public static final int Session_Response0_VALUE = 1;
    /**
     * <code>Session_Command1 = 2;</code>
     */
    public static final int Session_Command1_VALUE = 2;
    /**
     * <code>Session_Response1 = 3;</code>
     */
    public static final int Session_Response1_VALUE = 3;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Sec1MsgType valueOf(int value) {
      return forNumber(value);
    }

    public static Sec1MsgType forNumber(int value) {
      switch (value) {
        case 0: return Session_Command0;
        case 1: return Session_Response0;
        case 2: return Session_Command1;
        case 3: return Session_Response1;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Sec1MsgType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Sec1MsgType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Sec1MsgType>() {
            @Override
            public Sec1MsgType findValueByNumber(int number) {
              return Sec1MsgType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return Sec1MsgTypeVerifier.INSTANCE;
    }

    private static final class Sec1MsgTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new Sec1MsgTypeVerifier();
            @Override
            public boolean isInRange(int number) {
              return Sec1MsgType.forNumber(number) != null;
            }
          };

    private final int value;

    private Sec1MsgType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:Sec1MsgType)
  }

  public interface SessionCmd1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:SessionCmd1)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bytes client_verify_data = 2;</code>
     */
    com.google.protobuf.ByteString getClientVerifyData();
  }
  /**
   * Protobuf type {@code SessionCmd1}
   */
  public  static final class SessionCmd1 extends
      com.google.protobuf.GeneratedMessageLite<
          SessionCmd1, SessionCmd1.Builder> implements
      // @@protoc_insertion_point(message_implements:SessionCmd1)
      SessionCmd1OrBuilder {
    private SessionCmd1() {
      clientVerifyData_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int CLIENT_VERIFY_DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString clientVerifyData_;
    /**
     * <code>bytes client_verify_data = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString getClientVerifyData() {
      return clientVerifyData_;
    }
    /**
     * <code>bytes client_verify_data = 2;</code>
     */
    private void setClientVerifyData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientVerifyData_ = value;
    }
    /**
     * <code>bytes client_verify_data = 2;</code>
     */
    private void clearClientVerifyData() {
      
      clientVerifyData_ = getDefaultInstance().getClientVerifyData();
    }

    public static Sec1.SessionCmd1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.SessionCmd1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.SessionCmd1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.SessionCmd1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.SessionCmd1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.SessionCmd1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.SessionCmd1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Sec1.SessionCmd1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Sec1.SessionCmd1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Sec1.SessionCmd1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Sec1.SessionCmd1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Sec1.SessionCmd1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Sec1.SessionCmd1 prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code SessionCmd1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Sec1.SessionCmd1, Builder> implements
        // @@protoc_insertion_point(builder_implements:SessionCmd1)
        Sec1.SessionCmd1OrBuilder {
      // Construct using Sec1.SessionCmd1.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bytes client_verify_data = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString getClientVerifyData() {
        return instance.getClientVerifyData();
      }
      /**
       * <code>bytes client_verify_data = 2;</code>
       */
      public Builder setClientVerifyData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClientVerifyData(value);
        return this;
      }
      /**
       * <code>bytes client_verify_data = 2;</code>
       */
      public Builder clearClientVerifyData() {
        copyOnWrite();
        instance.clearClientVerifyData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SessionCmd1)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Sec1.SessionCmd1();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "clientVerifyData_",
            };
            String info =
                "\u0000\u0001\u0000\u0000\u0002\u0002\u0001\u0000\u0000\u0000\u0002\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Sec1.SessionCmd1> parser = PARSER;
          if (parser == null) {
            synchronized (Sec1.SessionCmd1.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SessionCmd1)
    private static final Sec1.SessionCmd1 DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new SessionCmd1();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SessionCmd1.class, DEFAULT_INSTANCE);
    }
    public static Sec1.SessionCmd1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SessionCmd1> PARSER;

    public static com.google.protobuf.Parser<SessionCmd1> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SessionResp1OrBuilder extends
      // @@protoc_insertion_point(interface_extends:SessionResp1)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.Status status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.Status status = 1;</code>
     */
    Constants.Status getStatus();

    /**
     * <code>bytes device_verify_data = 3;</code>
     */
    com.google.protobuf.ByteString getDeviceVerifyData();
  }
  /**
   * Protobuf type {@code SessionResp1}
   */
  public  static final class SessionResp1 extends
      com.google.protobuf.GeneratedMessageLite<
          SessionResp1, SessionResp1.Builder> implements
      // @@protoc_insertion_point(message_implements:SessionResp1)
      SessionResp1OrBuilder {
    private SessionResp1() {
      deviceVerifyData_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.Status status = 1;</code>
     */
    @Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    @Override
    public Constants.Status getStatus() {
      Constants.Status result = Constants.Status.forNumber(status_);
      return result == null ? Constants.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void setStatus(Constants.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public static final int DEVICE_VERIFY_DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString deviceVerifyData_;
    /**
     * <code>bytes device_verify_data = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString getDeviceVerifyData() {
      return deviceVerifyData_;
    }
    /**
     * <code>bytes device_verify_data = 3;</code>
     */
    private void setDeviceVerifyData(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceVerifyData_ = value;
    }
    /**
     * <code>bytes device_verify_data = 3;</code>
     */
    private void clearDeviceVerifyData() {
      
      deviceVerifyData_ = getDefaultInstance().getDeviceVerifyData();
    }

    public static Sec1.SessionResp1 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.SessionResp1 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.SessionResp1 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.SessionResp1 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.SessionResp1 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.SessionResp1 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.SessionResp1 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Sec1.SessionResp1 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Sec1.SessionResp1 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Sec1.SessionResp1 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Sec1.SessionResp1 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Sec1.SessionResp1 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Sec1.SessionResp1 prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code SessionResp1}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Sec1.SessionResp1, Builder> implements
        // @@protoc_insertion_point(builder_implements:SessionResp1)
        Sec1.SessionResp1OrBuilder {
      // Construct using Sec1.SessionResp1.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.Status status = 1;</code>
       */
      @Override
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>.Status status = 1;</code>
       */
      @Override
      public Constants.Status getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder setStatus(Constants.Status value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>bytes device_verify_data = 3;</code>
       */
      @Override
      public com.google.protobuf.ByteString getDeviceVerifyData() {
        return instance.getDeviceVerifyData();
      }
      /**
       * <code>bytes device_verify_data = 3;</code>
       */
      public Builder setDeviceVerifyData(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceVerifyData(value);
        return this;
      }
      /**
       * <code>bytes device_verify_data = 3;</code>
       */
      public Builder clearDeviceVerifyData() {
        copyOnWrite();
        instance.clearDeviceVerifyData();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SessionResp1)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Sec1.SessionResp1();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "status_",
              "deviceVerifyData_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0003\u0002\u0000\u0000\u0000\u0001\f\u0003\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Sec1.SessionResp1> parser = PARSER;
          if (parser == null) {
            synchronized (Sec1.SessionResp1.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SessionResp1)
    private static final Sec1.SessionResp1 DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new SessionResp1();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SessionResp1.class, DEFAULT_INSTANCE);
    }
    public static Sec1.SessionResp1 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SessionResp1> PARSER;

    public static com.google.protobuf.Parser<SessionResp1> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SessionCmd0OrBuilder extends
      // @@protoc_insertion_point(interface_extends:SessionCmd0)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bytes client_pubkey = 1;</code>
     */
    com.google.protobuf.ByteString getClientPubkey();
  }
  /**
   * Protobuf type {@code SessionCmd0}
   */
  public  static final class SessionCmd0 extends
      com.google.protobuf.GeneratedMessageLite<
          SessionCmd0, SessionCmd0.Builder> implements
      // @@protoc_insertion_point(message_implements:SessionCmd0)
      SessionCmd0OrBuilder {
    private SessionCmd0() {
      clientPubkey_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int CLIENT_PUBKEY_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString clientPubkey_;
    /**
     * <code>bytes client_pubkey = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString getClientPubkey() {
      return clientPubkey_;
    }
    /**
     * <code>bytes client_pubkey = 1;</code>
     */
    private void setClientPubkey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientPubkey_ = value;
    }
    /**
     * <code>bytes client_pubkey = 1;</code>
     */
    private void clearClientPubkey() {
      
      clientPubkey_ = getDefaultInstance().getClientPubkey();
    }

    public static Sec1.SessionCmd0 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.SessionCmd0 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.SessionCmd0 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.SessionCmd0 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.SessionCmd0 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.SessionCmd0 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.SessionCmd0 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Sec1.SessionCmd0 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Sec1.SessionCmd0 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Sec1.SessionCmd0 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Sec1.SessionCmd0 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Sec1.SessionCmd0 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Sec1.SessionCmd0 prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code SessionCmd0}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Sec1.SessionCmd0, Builder> implements
        // @@protoc_insertion_point(builder_implements:SessionCmd0)
        Sec1.SessionCmd0OrBuilder {
      // Construct using Sec1.SessionCmd0.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bytes client_pubkey = 1;</code>
       */
      @Override
      public com.google.protobuf.ByteString getClientPubkey() {
        return instance.getClientPubkey();
      }
      /**
       * <code>bytes client_pubkey = 1;</code>
       */
      public Builder setClientPubkey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClientPubkey(value);
        return this;
      }
      /**
       * <code>bytes client_pubkey = 1;</code>
       */
      public Builder clearClientPubkey() {
        copyOnWrite();
        instance.clearClientPubkey();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SessionCmd0)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Sec1.SessionCmd0();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "clientPubkey_",
            };
            String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Sec1.SessionCmd0> parser = PARSER;
          if (parser == null) {
            synchronized (Sec1.SessionCmd0.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SessionCmd0)
    private static final Sec1.SessionCmd0 DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new SessionCmd0();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SessionCmd0.class, DEFAULT_INSTANCE);
    }
    public static Sec1.SessionCmd0 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SessionCmd0> PARSER;

    public static com.google.protobuf.Parser<SessionCmd0> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SessionResp0OrBuilder extends
      // @@protoc_insertion_point(interface_extends:SessionResp0)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.Status status = 1;</code>
     */
    int getStatusValue();
    /**
     * <code>.Status status = 1;</code>
     */
    Constants.Status getStatus();

    /**
     * <code>bytes device_pubkey = 2;</code>
     */
    com.google.protobuf.ByteString getDevicePubkey();

    /**
     * <code>bytes device_random = 3;</code>
     */
    com.google.protobuf.ByteString getDeviceRandom();
  }
  /**
   * Protobuf type {@code SessionResp0}
   */
  public  static final class SessionResp0 extends
      com.google.protobuf.GeneratedMessageLite<
          SessionResp0, SessionResp0.Builder> implements
      // @@protoc_insertion_point(message_implements:SessionResp0)
      SessionResp0OrBuilder {
    private SessionResp0() {
      devicePubkey_ = com.google.protobuf.ByteString.EMPTY;
      deviceRandom_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_;
    /**
     * <code>.Status status = 1;</code>
     */
    @Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    @Override
    public Constants.Status getStatus() {
      Constants.Status result = Constants.Status.forNumber(status_);
      return result == null ? Constants.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void setStatus(Constants.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
    }
    /**
     * <code>.Status status = 1;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public static final int DEVICE_PUBKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString devicePubkey_;
    /**
     * <code>bytes device_pubkey = 2;</code>
     */
    @Override
    public com.google.protobuf.ByteString getDevicePubkey() {
      return devicePubkey_;
    }
    /**
     * <code>bytes device_pubkey = 2;</code>
     */
    private void setDevicePubkey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      devicePubkey_ = value;
    }
    /**
     * <code>bytes device_pubkey = 2;</code>
     */
    private void clearDevicePubkey() {
      
      devicePubkey_ = getDefaultInstance().getDevicePubkey();
    }

    public static final int DEVICE_RANDOM_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString deviceRandom_;
    /**
     * <code>bytes device_random = 3;</code>
     */
    @Override
    public com.google.protobuf.ByteString getDeviceRandom() {
      return deviceRandom_;
    }
    /**
     * <code>bytes device_random = 3;</code>
     */
    private void setDeviceRandom(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceRandom_ = value;
    }
    /**
     * <code>bytes device_random = 3;</code>
     */
    private void clearDeviceRandom() {
      
      deviceRandom_ = getDefaultInstance().getDeviceRandom();
    }

    public static Sec1.SessionResp0 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.SessionResp0 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.SessionResp0 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.SessionResp0 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.SessionResp0 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.SessionResp0 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.SessionResp0 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Sec1.SessionResp0 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Sec1.SessionResp0 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Sec1.SessionResp0 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Sec1.SessionResp0 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Sec1.SessionResp0 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Sec1.SessionResp0 prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code SessionResp0}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Sec1.SessionResp0, Builder> implements
        // @@protoc_insertion_point(builder_implements:SessionResp0)
        Sec1.SessionResp0OrBuilder {
      // Construct using Sec1.SessionResp0.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.Status status = 1;</code>
       */
      @Override
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>.Status status = 1;</code>
       */
      @Override
      public Constants.Status getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder setStatus(Constants.Status value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>.Status status = 1;</code>
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>bytes device_pubkey = 2;</code>
       */
      @Override
      public com.google.protobuf.ByteString getDevicePubkey() {
        return instance.getDevicePubkey();
      }
      /**
       * <code>bytes device_pubkey = 2;</code>
       */
      public Builder setDevicePubkey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDevicePubkey(value);
        return this;
      }
      /**
       * <code>bytes device_pubkey = 2;</code>
       */
      public Builder clearDevicePubkey() {
        copyOnWrite();
        instance.clearDevicePubkey();
        return this;
      }

      /**
       * <code>bytes device_random = 3;</code>
       */
      @Override
      public com.google.protobuf.ByteString getDeviceRandom() {
        return instance.getDeviceRandom();
      }
      /**
       * <code>bytes device_random = 3;</code>
       */
      public Builder setDeviceRandom(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDeviceRandom(value);
        return this;
      }
      /**
       * <code>bytes device_random = 3;</code>
       */
      public Builder clearDeviceRandom() {
        copyOnWrite();
        instance.clearDeviceRandom();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SessionResp0)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Sec1.SessionResp0();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "status_",
              "devicePubkey_",
              "deviceRandom_",
            };
            String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\f\u0002\n\u0003" +
                "\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Sec1.SessionResp0> parser = PARSER;
          if (parser == null) {
            synchronized (Sec1.SessionResp0.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SessionResp0)
    private static final Sec1.SessionResp0 DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new SessionResp0();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SessionResp0.class, DEFAULT_INSTANCE);
    }
    public static Sec1.SessionResp0 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SessionResp0> PARSER;

    public static com.google.protobuf.Parser<SessionResp0> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface Sec1PayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Sec1Payload)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.Sec1MsgType msg = 1;</code>
     */
    int getMsgValue();
    /**
     * <code>.Sec1MsgType msg = 1;</code>
     */
    Sec1.Sec1MsgType getMsg();

    /**
     * <code>.SessionCmd0 sc0 = 20;</code>
     */
    boolean hasSc0();
    /**
     * <code>.SessionCmd0 sc0 = 20;</code>
     */
    Sec1.SessionCmd0 getSc0();

    /**
     * <code>.SessionResp0 sr0 = 21;</code>
     */
    boolean hasSr0();
    /**
     * <code>.SessionResp0 sr0 = 21;</code>
     */
    Sec1.SessionResp0 getSr0();

    /**
     * <code>.SessionCmd1 sc1 = 22;</code>
     */
    boolean hasSc1();
    /**
     * <code>.SessionCmd1 sc1 = 22;</code>
     */
    Sec1.SessionCmd1 getSc1();

    /**
     * <code>.SessionResp1 sr1 = 23;</code>
     */
    boolean hasSr1();
    /**
     * <code>.SessionResp1 sr1 = 23;</code>
     */
    Sec1.SessionResp1 getSr1();

    public Sec1.Sec1Payload.PayloadCase getPayloadCase();
  }
  /**
   * Protobuf type {@code Sec1Payload}
   */
  public  static final class Sec1Payload extends
      com.google.protobuf.GeneratedMessageLite<
          Sec1Payload, Sec1Payload.Builder> implements
      // @@protoc_insertion_point(message_implements:Sec1Payload)
      Sec1PayloadOrBuilder {
    private Sec1Payload() {
    }
    private int payloadCase_ = 0;
    private Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      SC0(20),
      SR0(21),
      SC1(22),
      SR1(23),
      PAYLOAD_NOT_SET(0);
      private final int value;
      private PayloadCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static PayloadCase valueOf(int value) {
        return forNumber(value);
      }

      public static PayloadCase forNumber(int value) {
        switch (value) {
          case 20: return SC0;
          case 21: return SR0;
          case 22: return SC1;
          case 23: return SR1;
          case 0: return PAYLOAD_NOT_SET;
          default: return null;
        }
      }
      @Override
      public int getNumber() {
        return this.value;
      }
    };

    @Override
    public PayloadCase
    getPayloadCase() {
      return PayloadCase.forNumber(
          payloadCase_);
    }

    private void clearPayload() {
      payloadCase_ = 0;
      payload_ = null;
    }

    public static final int MSG_FIELD_NUMBER = 1;
    private int msg_;
    /**
     * <code>.Sec1MsgType msg = 1;</code>
     */
    @Override
    public int getMsgValue() {
      return msg_;
    }
    /**
     * <code>.Sec1MsgType msg = 1;</code>
     */
    @Override
    public Sec1.Sec1MsgType getMsg() {
      Sec1.Sec1MsgType result = Sec1.Sec1MsgType.forNumber(msg_);
      return result == null ? Sec1.Sec1MsgType.UNRECOGNIZED : result;
    }
    /**
     * <code>.Sec1MsgType msg = 1;</code>
     */
    private void setMsgValue(int value) {
        msg_ = value;
    }
    /**
     * <code>.Sec1MsgType msg = 1;</code>
     */
    private void setMsg(Sec1.Sec1MsgType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      msg_ = value.getNumber();
    }
    /**
     * <code>.Sec1MsgType msg = 1;</code>
     */
    private void clearMsg() {
      
      msg_ = 0;
    }

    public static final int SC0_FIELD_NUMBER = 20;
    /**
     * <code>.SessionCmd0 sc0 = 20;</code>
     */
    @Override
    public boolean hasSc0() {
      return payloadCase_ == 20;
    }
    /**
     * <code>.SessionCmd0 sc0 = 20;</code>
     */
    @Override
    public Sec1.SessionCmd0 getSc0() {
      if (payloadCase_ == 20) {
         return (Sec1.SessionCmd0) payload_;
      }
      return Sec1.SessionCmd0.getDefaultInstance();
    }
    /**
     * <code>.SessionCmd0 sc0 = 20;</code>
     */
    private void setSc0(Sec1.SessionCmd0 value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 20;
    }
    /**
     * <code>.SessionCmd0 sc0 = 20;</code>
     */
    private void setSc0(
        Sec1.SessionCmd0.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 20;
    }
    /**
     * <code>.SessionCmd0 sc0 = 20;</code>
     */
    private void mergeSc0(Sec1.SessionCmd0 value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 20 &&
          payload_ != Sec1.SessionCmd0.getDefaultInstance()) {
        payload_ = Sec1.SessionCmd0.newBuilder((Sec1.SessionCmd0) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 20;
    }
    /**
     * <code>.SessionCmd0 sc0 = 20;</code>
     */
    private void clearSc0() {
      if (payloadCase_ == 20) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static final int SR0_FIELD_NUMBER = 21;
    /**
     * <code>.SessionResp0 sr0 = 21;</code>
     */
    @Override
    public boolean hasSr0() {
      return payloadCase_ == 21;
    }
    /**
     * <code>.SessionResp0 sr0 = 21;</code>
     */
    @Override
    public Sec1.SessionResp0 getSr0() {
      if (payloadCase_ == 21) {
         return (Sec1.SessionResp0) payload_;
      }
      return Sec1.SessionResp0.getDefaultInstance();
    }
    /**
     * <code>.SessionResp0 sr0 = 21;</code>
     */
    private void setSr0(Sec1.SessionResp0 value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 21;
    }
    /**
     * <code>.SessionResp0 sr0 = 21;</code>
     */
    private void setSr0(
        Sec1.SessionResp0.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 21;
    }
    /**
     * <code>.SessionResp0 sr0 = 21;</code>
     */
    private void mergeSr0(Sec1.SessionResp0 value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 21 &&
          payload_ != Sec1.SessionResp0.getDefaultInstance()) {
        payload_ = Sec1.SessionResp0.newBuilder((Sec1.SessionResp0) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 21;
    }
    /**
     * <code>.SessionResp0 sr0 = 21;</code>
     */
    private void clearSr0() {
      if (payloadCase_ == 21) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static final int SC1_FIELD_NUMBER = 22;
    /**
     * <code>.SessionCmd1 sc1 = 22;</code>
     */
    @Override
    public boolean hasSc1() {
      return payloadCase_ == 22;
    }
    /**
     * <code>.SessionCmd1 sc1 = 22;</code>
     */
    @Override
    public Sec1.SessionCmd1 getSc1() {
      if (payloadCase_ == 22) {
         return (Sec1.SessionCmd1) payload_;
      }
      return Sec1.SessionCmd1.getDefaultInstance();
    }
    /**
     * <code>.SessionCmd1 sc1 = 22;</code>
     */
    private void setSc1(Sec1.SessionCmd1 value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 22;
    }
    /**
     * <code>.SessionCmd1 sc1 = 22;</code>
     */
    private void setSc1(
        Sec1.SessionCmd1.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 22;
    }
    /**
     * <code>.SessionCmd1 sc1 = 22;</code>
     */
    private void mergeSc1(Sec1.SessionCmd1 value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 22 &&
          payload_ != Sec1.SessionCmd1.getDefaultInstance()) {
        payload_ = Sec1.SessionCmd1.newBuilder((Sec1.SessionCmd1) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 22;
    }
    /**
     * <code>.SessionCmd1 sc1 = 22;</code>
     */
    private void clearSc1() {
      if (payloadCase_ == 22) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static final int SR1_FIELD_NUMBER = 23;
    /**
     * <code>.SessionResp1 sr1 = 23;</code>
     */
    @Override
    public boolean hasSr1() {
      return payloadCase_ == 23;
    }
    /**
     * <code>.SessionResp1 sr1 = 23;</code>
     */
    @Override
    public Sec1.SessionResp1 getSr1() {
      if (payloadCase_ == 23) {
         return (Sec1.SessionResp1) payload_;
      }
      return Sec1.SessionResp1.getDefaultInstance();
    }
    /**
     * <code>.SessionResp1 sr1 = 23;</code>
     */
    private void setSr1(Sec1.SessionResp1 value) {
      if (value == null) {
        throw new NullPointerException();
      }
      payload_ = value;
      payloadCase_ = 23;
    }
    /**
     * <code>.SessionResp1 sr1 = 23;</code>
     */
    private void setSr1(
        Sec1.SessionResp1.Builder builderForValue) {
      payload_ = builderForValue.build();
      payloadCase_ = 23;
    }
    /**
     * <code>.SessionResp1 sr1 = 23;</code>
     */
    private void mergeSr1(Sec1.SessionResp1 value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (payloadCase_ == 23 &&
          payload_ != Sec1.SessionResp1.getDefaultInstance()) {
        payload_ = Sec1.SessionResp1.newBuilder((Sec1.SessionResp1) payload_)
            .mergeFrom(value).buildPartial();
      } else {
        payload_ = value;
      }
      payloadCase_ = 23;
    }
    /**
     * <code>.SessionResp1 sr1 = 23;</code>
     */
    private void clearSr1() {
      if (payloadCase_ == 23) {
        payloadCase_ = 0;
        payload_ = null;
      }
    }

    public static Sec1.Sec1Payload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.Sec1Payload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.Sec1Payload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.Sec1Payload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.Sec1Payload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Sec1.Sec1Payload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Sec1.Sec1Payload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Sec1.Sec1Payload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Sec1.Sec1Payload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Sec1.Sec1Payload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Sec1.Sec1Payload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Sec1.Sec1Payload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Sec1.Sec1Payload prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code Sec1Payload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Sec1.Sec1Payload, Builder> implements
        // @@protoc_insertion_point(builder_implements:Sec1Payload)
        Sec1.Sec1PayloadOrBuilder {
      // Construct using Sec1.Sec1Payload.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @Override
      public PayloadCase
          getPayloadCase() {
        return instance.getPayloadCase();
      }

      public Builder clearPayload() {
        copyOnWrite();
        instance.clearPayload();
        return this;
      }


      /**
       * <code>.Sec1MsgType msg = 1;</code>
       */
      @Override
      public int getMsgValue() {
        return instance.getMsgValue();
      }
      /**
       * <code>.Sec1MsgType msg = 1;</code>
       */
      public Builder setMsgValue(int value) {
        copyOnWrite();
        instance.setMsgValue(value);
        return this;
      }
      /**
       * <code>.Sec1MsgType msg = 1;</code>
       */
      @Override
      public Sec1.Sec1MsgType getMsg() {
        return instance.getMsg();
      }
      /**
       * <code>.Sec1MsgType msg = 1;</code>
       */
      public Builder setMsg(Sec1.Sec1MsgType value) {
        copyOnWrite();
        instance.setMsg(value);
        return this;
      }
      /**
       * <code>.Sec1MsgType msg = 1;</code>
       */
      public Builder clearMsg() {
        copyOnWrite();
        instance.clearMsg();
        return this;
      }

      /**
       * <code>.SessionCmd0 sc0 = 20;</code>
       */
      @Override
      public boolean hasSc0() {
        return instance.hasSc0();
      }
      /**
       * <code>.SessionCmd0 sc0 = 20;</code>
       */
      @Override
      public Sec1.SessionCmd0 getSc0() {
        return instance.getSc0();
      }
      /**
       * <code>.SessionCmd0 sc0 = 20;</code>
       */
      public Builder setSc0(Sec1.SessionCmd0 value) {
        copyOnWrite();
        instance.setSc0(value);
        return this;
      }
      /**
       * <code>.SessionCmd0 sc0 = 20;</code>
       */
      public Builder setSc0(
          Sec1.SessionCmd0.Builder builderForValue) {
        copyOnWrite();
        instance.setSc0(builderForValue);
        return this;
      }
      /**
       * <code>.SessionCmd0 sc0 = 20;</code>
       */
      public Builder mergeSc0(Sec1.SessionCmd0 value) {
        copyOnWrite();
        instance.mergeSc0(value);
        return this;
      }
      /**
       * <code>.SessionCmd0 sc0 = 20;</code>
       */
      public Builder clearSc0() {
        copyOnWrite();
        instance.clearSc0();
        return this;
      }

      /**
       * <code>.SessionResp0 sr0 = 21;</code>
       */
      @Override
      public boolean hasSr0() {
        return instance.hasSr0();
      }
      /**
       * <code>.SessionResp0 sr0 = 21;</code>
       */
      @Override
      public Sec1.SessionResp0 getSr0() {
        return instance.getSr0();
      }
      /**
       * <code>.SessionResp0 sr0 = 21;</code>
       */
      public Builder setSr0(Sec1.SessionResp0 value) {
        copyOnWrite();
        instance.setSr0(value);
        return this;
      }
      /**
       * <code>.SessionResp0 sr0 = 21;</code>
       */
      public Builder setSr0(
          Sec1.SessionResp0.Builder builderForValue) {
        copyOnWrite();
        instance.setSr0(builderForValue);
        return this;
      }
      /**
       * <code>.SessionResp0 sr0 = 21;</code>
       */
      public Builder mergeSr0(Sec1.SessionResp0 value) {
        copyOnWrite();
        instance.mergeSr0(value);
        return this;
      }
      /**
       * <code>.SessionResp0 sr0 = 21;</code>
       */
      public Builder clearSr0() {
        copyOnWrite();
        instance.clearSr0();
        return this;
      }

      /**
       * <code>.SessionCmd1 sc1 = 22;</code>
       */
      @Override
      public boolean hasSc1() {
        return instance.hasSc1();
      }
      /**
       * <code>.SessionCmd1 sc1 = 22;</code>
       */
      @Override
      public Sec1.SessionCmd1 getSc1() {
        return instance.getSc1();
      }
      /**
       * <code>.SessionCmd1 sc1 = 22;</code>
       */
      public Builder setSc1(Sec1.SessionCmd1 value) {
        copyOnWrite();
        instance.setSc1(value);
        return this;
      }
      /**
       * <code>.SessionCmd1 sc1 = 22;</code>
       */
      public Builder setSc1(
          Sec1.SessionCmd1.Builder builderForValue) {
        copyOnWrite();
        instance.setSc1(builderForValue);
        return this;
      }
      /**
       * <code>.SessionCmd1 sc1 = 22;</code>
       */
      public Builder mergeSc1(Sec1.SessionCmd1 value) {
        copyOnWrite();
        instance.mergeSc1(value);
        return this;
      }
      /**
       * <code>.SessionCmd1 sc1 = 22;</code>
       */
      public Builder clearSc1() {
        copyOnWrite();
        instance.clearSc1();
        return this;
      }

      /**
       * <code>.SessionResp1 sr1 = 23;</code>
       */
      @Override
      public boolean hasSr1() {
        return instance.hasSr1();
      }
      /**
       * <code>.SessionResp1 sr1 = 23;</code>
       */
      @Override
      public Sec1.SessionResp1 getSr1() {
        return instance.getSr1();
      }
      /**
       * <code>.SessionResp1 sr1 = 23;</code>
       */
      public Builder setSr1(Sec1.SessionResp1 value) {
        copyOnWrite();
        instance.setSr1(value);
        return this;
      }
      /**
       * <code>.SessionResp1 sr1 = 23;</code>
       */
      public Builder setSr1(
          Sec1.SessionResp1.Builder builderForValue) {
        copyOnWrite();
        instance.setSr1(builderForValue);
        return this;
      }
      /**
       * <code>.SessionResp1 sr1 = 23;</code>
       */
      public Builder mergeSr1(Sec1.SessionResp1 value) {
        copyOnWrite();
        instance.mergeSr1(value);
        return this;
      }
      /**
       * <code>.SessionResp1 sr1 = 23;</code>
       */
      public Builder clearSr1() {
        copyOnWrite();
        instance.clearSr1();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Sec1Payload)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Sec1.Sec1Payload();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "payload_",
              "payloadCase_",
              "msg_",
              Sec1.SessionCmd0.class,
              Sec1.SessionResp0.class,
              Sec1.SessionCmd1.class,
              Sec1.SessionResp1.class,
            };
            String info =
                "\u0000\u0005\u0001\u0000\u0001\u0017\u0005\u0000\u0000\u0000\u0001\f\u0014<\u0000" +
                "\u0015<\u0000\u0016<\u0000\u0017<\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Sec1.Sec1Payload> parser = PARSER;
          if (parser == null) {
            synchronized (Sec1.Sec1Payload.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Sec1Payload)
    private static final Sec1.Sec1Payload DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new Sec1Payload();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Sec1Payload.class, DEFAULT_INSTANCE);
    }
    public static Sec1.Sec1Payload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Sec1Payload> PARSER;

    public static com.google.protobuf.Parser<Sec1Payload> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
