// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: session.proto

package com.ash93.esp32_ble_provisioning_plugin.ESPProvision.espressif;

public final class Session {
  private Session() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code SecSchemeVersion}
   */
  public enum SecSchemeVersion
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <pre>
     * Unsecured - plaintext communication 
     * </pre>
     *
     * <code>SecScheme0 = 0;</code>
     */
    SecScheme0(0),
    /**
     * <pre>
     * Security scheme 1 - Curve25519 + AES-256-CTR
     * </pre>
     *
     * <code>SecScheme1 = 1;</code>
     */
    SecScheme1(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Unsecured - plaintext communication 
     * </pre>
     *
     * <code>SecScheme0 = 0;</code>
     */
    public static final int SecScheme0_VALUE = 0;
    /**
     * <pre>
     * Security scheme 1 - Curve25519 + AES-256-CTR
     * </pre>
     *
     * <code>SecScheme1 = 1;</code>
     */
    public static final int SecScheme1_VALUE = 1;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static SecSchemeVersion valueOf(int value) {
      return forNumber(value);
    }

    public static SecSchemeVersion forNumber(int value) {
      switch (value) {
        case 0: return SecScheme0;
        case 1: return SecScheme1;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SecSchemeVersion>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SecSchemeVersion> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SecSchemeVersion>() {
            @Override
            public SecSchemeVersion findValueByNumber(int number) {
              return SecSchemeVersion.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return SecSchemeVersionVerifier.INSTANCE;
    }

    private static final class SecSchemeVersionVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new SecSchemeVersionVerifier();
            @Override
            public boolean isInRange(int number) {
              return SecSchemeVersion.forNumber(number) != null;
            }
          };

    private final int value;

    private SecSchemeVersion(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SecSchemeVersion)
  }

  public interface SessionDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SessionData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.SecSchemeVersion sec_ver = 2;</code>
     */
    int getSecVerValue();
    /**
     * <code>.SecSchemeVersion sec_ver = 2;</code>
     */
    Session.SecSchemeVersion getSecVer();

    /**
     * <code>.Sec0Payload sec0 = 10;</code>
     */
    boolean hasSec0();
    /**
     * <code>.Sec0Payload sec0 = 10;</code>
     */
    Sec0.Sec0Payload getSec0();

    /**
     * <code>.Sec1Payload sec1 = 11;</code>
     */
    boolean hasSec1();
    /**
     * <code>.Sec1Payload sec1 = 11;</code>
     */
    Sec1.Sec1Payload getSec1();

    public Session.SessionData.ProtoCase getProtoCase();
  }
  /**
   * Protobuf type {@code SessionData}
   */
  public  static final class SessionData extends
      com.google.protobuf.GeneratedMessageLite<
          SessionData, SessionData.Builder> implements
      // @@protoc_insertion_point(message_implements:SessionData)
      SessionDataOrBuilder {
    private SessionData() {
    }
    private int protoCase_ = 0;
    private Object proto_;
    public enum ProtoCase
        implements com.google.protobuf.Internal.EnumLite {
      SEC0(10),
      SEC1(11),
      PROTO_NOT_SET(0);
      private final int value;
      private ProtoCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static ProtoCase valueOf(int value) {
        return forNumber(value);
      }

      public static ProtoCase forNumber(int value) {
        switch (value) {
          case 10: return SEC0;
          case 11: return SEC1;
          case 0: return PROTO_NOT_SET;
          default: return null;
        }
      }
      @Override
      public int getNumber() {
        return this.value;
      }
    };

    @Override
    public ProtoCase
    getProtoCase() {
      return ProtoCase.forNumber(
          protoCase_);
    }

    private void clearProto() {
      protoCase_ = 0;
      proto_ = null;
    }

    public static final int SEC_VER_FIELD_NUMBER = 2;
    private int secVer_;
    /**
     * <code>.SecSchemeVersion sec_ver = 2;</code>
     */
    @Override
    public int getSecVerValue() {
      return secVer_;
    }
    /**
     * <code>.SecSchemeVersion sec_ver = 2;</code>
     */
    @Override
    public Session.SecSchemeVersion getSecVer() {
      Session.SecSchemeVersion result = Session.SecSchemeVersion.forNumber(secVer_);
      return result == null ? Session.SecSchemeVersion.UNRECOGNIZED : result;
    }
    /**
     * <code>.SecSchemeVersion sec_ver = 2;</code>
     */
    private void setSecVerValue(int value) {
        secVer_ = value;
    }
    /**
     * <code>.SecSchemeVersion sec_ver = 2;</code>
     */
    private void setSecVer(Session.SecSchemeVersion value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      secVer_ = value.getNumber();
    }
    /**
     * <code>.SecSchemeVersion sec_ver = 2;</code>
     */
    private void clearSecVer() {
      
      secVer_ = 0;
    }

    public static final int SEC0_FIELD_NUMBER = 10;
    /**
     * <code>.Sec0Payload sec0 = 10;</code>
     */
    @Override
    public boolean hasSec0() {
      return protoCase_ == 10;
    }
    /**
     * <code>.Sec0Payload sec0 = 10;</code>
     */
    @Override
    public Sec0.Sec0Payload getSec0() {
      if (protoCase_ == 10) {
         return (Sec0.Sec0Payload) proto_;
      }
      return Sec0.Sec0Payload.getDefaultInstance();
    }
    /**
     * <code>.Sec0Payload sec0 = 10;</code>
     */
    private void setSec0(Sec0.Sec0Payload value) {
      if (value == null) {
        throw new NullPointerException();
      }
      proto_ = value;
      protoCase_ = 10;
    }
    /**
     * <code>.Sec0Payload sec0 = 10;</code>
     */
    private void setSec0(
        Sec0.Sec0Payload.Builder builderForValue) {
      proto_ = builderForValue.build();
      protoCase_ = 10;
    }
    /**
     * <code>.Sec0Payload sec0 = 10;</code>
     */
    private void mergeSec0(Sec0.Sec0Payload value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (protoCase_ == 10 &&
          proto_ != Sec0.Sec0Payload.getDefaultInstance()) {
        proto_ = Sec0.Sec0Payload.newBuilder((Sec0.Sec0Payload) proto_)
            .mergeFrom(value).buildPartial();
      } else {
        proto_ = value;
      }
      protoCase_ = 10;
    }
    /**
     * <code>.Sec0Payload sec0 = 10;</code>
     */
    private void clearSec0() {
      if (protoCase_ == 10) {
        protoCase_ = 0;
        proto_ = null;
      }
    }

    public static final int SEC1_FIELD_NUMBER = 11;
    /**
     * <code>.Sec1Payload sec1 = 11;</code>
     */
    @Override
    public boolean hasSec1() {
      return protoCase_ == 11;
    }
    /**
     * <code>.Sec1Payload sec1 = 11;</code>
     */
    @Override
    public Sec1.Sec1Payload getSec1() {
      if (protoCase_ == 11) {
         return (Sec1.Sec1Payload) proto_;
      }
      return Sec1.Sec1Payload.getDefaultInstance();
    }
    /**
     * <code>.Sec1Payload sec1 = 11;</code>
     */
    private void setSec1(Sec1.Sec1Payload value) {
      if (value == null) {
        throw new NullPointerException();
      }
      proto_ = value;
      protoCase_ = 11;
    }
    /**
     * <code>.Sec1Payload sec1 = 11;</code>
     */
    private void setSec1(
        Sec1.Sec1Payload.Builder builderForValue) {
      proto_ = builderForValue.build();
      protoCase_ = 11;
    }
    /**
     * <code>.Sec1Payload sec1 = 11;</code>
     */
    private void mergeSec1(Sec1.Sec1Payload value) {
      if (value == null) {
        throw new NullPointerException();
      }
      if (protoCase_ == 11 &&
          proto_ != Sec1.Sec1Payload.getDefaultInstance()) {
        proto_ = Sec1.Sec1Payload.newBuilder((Sec1.Sec1Payload) proto_)
            .mergeFrom(value).buildPartial();
      } else {
        proto_ = value;
      }
      protoCase_ = 11;
    }
    /**
     * <code>.Sec1Payload sec1 = 11;</code>
     */
    private void clearSec1() {
      if (protoCase_ == 11) {
        protoCase_ = 0;
        proto_ = null;
      }
    }

    public static Session.SessionData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Session.SessionData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Session.SessionData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Session.SessionData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Session.SessionData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Session.SessionData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Session.SessionData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Session.SessionData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Session.SessionData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Session.SessionData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Session.SessionData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Session.SessionData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Session.SessionData prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code SessionData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Session.SessionData, Builder> implements
        // @@protoc_insertion_point(builder_implements:SessionData)
        Session.SessionDataOrBuilder {
      // Construct using Session.SessionData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      @Override
      public ProtoCase
          getProtoCase() {
        return instance.getProtoCase();
      }

      public Builder clearProto() {
        copyOnWrite();
        instance.clearProto();
        return this;
      }


      /**
       * <code>.SecSchemeVersion sec_ver = 2;</code>
       */
      @Override
      public int getSecVerValue() {
        return instance.getSecVerValue();
      }
      /**
       * <code>.SecSchemeVersion sec_ver = 2;</code>
       */
      public Builder setSecVerValue(int value) {
        copyOnWrite();
        instance.setSecVerValue(value);
        return this;
      }
      /**
       * <code>.SecSchemeVersion sec_ver = 2;</code>
       */
      @Override
      public Session.SecSchemeVersion getSecVer() {
        return instance.getSecVer();
      }
      /**
       * <code>.SecSchemeVersion sec_ver = 2;</code>
       */
      public Builder setSecVer(Session.SecSchemeVersion value) {
        copyOnWrite();
        instance.setSecVer(value);
        return this;
      }
      /**
       * <code>.SecSchemeVersion sec_ver = 2;</code>
       */
      public Builder clearSecVer() {
        copyOnWrite();
        instance.clearSecVer();
        return this;
      }

      /**
       * <code>.Sec0Payload sec0 = 10;</code>
       */
      @Override
      public boolean hasSec0() {
        return instance.hasSec0();
      }
      /**
       * <code>.Sec0Payload sec0 = 10;</code>
       */
      @Override
      public Sec0.Sec0Payload getSec0() {
        return instance.getSec0();
      }
      /**
       * <code>.Sec0Payload sec0 = 10;</code>
       */
      public Builder setSec0(Sec0.Sec0Payload value) {
        copyOnWrite();
        instance.setSec0(value);
        return this;
      }
      /**
       * <code>.Sec0Payload sec0 = 10;</code>
       */
      public Builder setSec0(
          Sec0.Sec0Payload.Builder builderForValue) {
        copyOnWrite();
        instance.setSec0(builderForValue);
        return this;
      }
      /**
       * <code>.Sec0Payload sec0 = 10;</code>
       */
      public Builder mergeSec0(Sec0.Sec0Payload value) {
        copyOnWrite();
        instance.mergeSec0(value);
        return this;
      }
      /**
       * <code>.Sec0Payload sec0 = 10;</code>
       */
      public Builder clearSec0() {
        copyOnWrite();
        instance.clearSec0();
        return this;
      }

      /**
       * <code>.Sec1Payload sec1 = 11;</code>
       */
      @Override
      public boolean hasSec1() {
        return instance.hasSec1();
      }
      /**
       * <code>.Sec1Payload sec1 = 11;</code>
       */
      @Override
      public Sec1.Sec1Payload getSec1() {
        return instance.getSec1();
      }
      /**
       * <code>.Sec1Payload sec1 = 11;</code>
       */
      public Builder setSec1(Sec1.Sec1Payload value) {
        copyOnWrite();
        instance.setSec1(value);
        return this;
      }
      /**
       * <code>.Sec1Payload sec1 = 11;</code>
       */
      public Builder setSec1(
          Sec1.Sec1Payload.Builder builderForValue) {
        copyOnWrite();
        instance.setSec1(builderForValue);
        return this;
      }
      /**
       * <code>.Sec1Payload sec1 = 11;</code>
       */
      public Builder mergeSec1(Sec1.Sec1Payload value) {
        copyOnWrite();
        instance.mergeSec1(value);
        return this;
      }
      /**
       * <code>.Sec1Payload sec1 = 11;</code>
       */
      public Builder clearSec1() {
        copyOnWrite();
        instance.clearSec1();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SessionData)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Session.SessionData();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "proto_",
              "protoCase_",
              "secVer_",
              Sec0.Sec0Payload.class,
              Sec1.Sec1Payload.class,
            };
            String info =
                "\u0000\u0003\u0001\u0000\u0002\u000b\u0003\u0000\u0000\u0000\u0002\f\n<\u0000\u000b" +
                "<\u0000";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Session.SessionData> parser = PARSER;
          if (parser == null) {
            synchronized (Session.SessionData.class) {
              parser = PARSER;
              if (parser == null) {
                parser = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SessionData)
    private static final Session.SessionData DEFAULT_INSTANCE;
    static {
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = new SessionData();
    }

    static {
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SessionData.class, DEFAULT_INSTANCE);
    }
    public static Session.SessionData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SessionData> PARSER;

    public static com.google.protobuf.Parser<SessionData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
