//package com.ash93.esp32_ble_provisioning_plugin.ESPProvisioning.espressif;// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: constants.proto
//
//import com.google.protobuf.*;
//
//public final class Constants {
//  private Constants() {}
//  public static void registerAllExtensions(
//      ExtensionRegistryLite registry) {
//  }
//  /**
//   * Protobuf enum {@code espressif.Status}
//   */
//  public enum Status
//      implements Internal.EnumLite {
//    /**
//     * <code>Success = 0;</code>
//     */
//    Success(0),
//    /**
//     * <code>InvalidSecScheme = 1;</code>
//     */
//    InvalidSecScheme(1),
//    /**
//     * <code>InvalidProto = 2;</code>
//     */
//    InvalidProto(2),
//    /**
//     * <code>TooManySessions = 3;</code>
//     */
//    TooManySessions(3),
//    /**
//     * <code>InvalidArgument = 4;</code>
//     */
//    InvalidArgument(4),
//    /**
//     * <code>InternalError = 5;</code>
//     */
//    InternalError(5),
//    /**
//     * <code>CryptoError = 6;</code>
//     */
//    CryptoError(6),
//    /**
//     * <code>InvalidSession = 7;</code>
//     */
//    InvalidSession(7),
//    UNRECOGNIZED(-1),
//    ;
//
//    /**
//     * <code>Success = 0;</code>
//     */
//    public static final int Success_VALUE = 0;
//    /**
//     * <code>InvalidSecScheme = 1;</code>
//     */
//    public static final int InvalidSecScheme_VALUE = 1;
//    /**
//     * <code>InvalidProto = 2;</code>
//     */
//    public static final int InvalidProto_VALUE = 2;
//    /**
//     * <code>TooManySessions = 3;</code>
//     */
//    public static final int TooManySessions_VALUE = 3;
//    /**
//     * <code>InvalidArgument = 4;</code>
//     */
//    public static final int InvalidArgument_VALUE = 4;
//    /**
//     * <code>InternalError = 5;</code>
//     */
//    public static final int InternalError_VALUE = 5;
//    /**
//     * <code>CryptoError = 6;</code>
//     */
//    public static final int CryptoError_VALUE = 6;
//    /**
//     * <code>InvalidSession = 7;</code>
//     */
//    public static final int InvalidSession_VALUE = 7;
//
//
//    public final int getNumber() {
//      return value;
//    }
//
//    /**
//     * @deprecated Use {@link #forNumber(int)} instead.
//     */
//    @java.lang.Deprecated
//    public static Status valueOf(int value) {
//      return forNumber(value);
//    }
//
//    public static Status forNumber(int value) {
//      switch (value) {
//        case 0: return Success;
//        case 1: return InvalidSecScheme;
//        case 2: return InvalidProto;
//        case 3: return TooManySessions;
//        case 4: return InvalidArgument;
//        case 5: return InternalError;
//        case 6: return CryptoError;
//        case 7: return InvalidSession;
//        default: return null;
//      }
//    }
//
//    public static Internal.EnumLiteMap<Status>
//        internalGetValueMap() {
//      return internalValueMap;
//    }
//    private static final Internal.EnumLiteMap<
//        Status> internalValueMap =
//          new Internal.EnumLiteMap<Status>() {
//            public Status findValueByNumber(int number) {
//              return Status.forNumber(number);
//            }
//          };
//
//    private final int value;
//
//    private Status(int value) {
//      this.value = value;
//    }
//
//    // @@protoc_insertion_point(enum_scope:espressif.Status)
//  }
//
//
//  static {
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
