//// Generated by the protocol buffer compiler.  DO NOT EDIT!
//// source: session.proto
//
//package com.ash93.esp32_ble_provisioning_plugin.ESPProvisioning.espressif;
//
//import com.google.protobuf.*;
//
//public final class Session {
//  private Session() {}
//  public static void registerAllExtensions(
//      ExtensionRegistryLite registry) {
//  }
//  /**
//   * Protobuf enum {@code SecSchemeVersion}
//   */
//  public enum SecSchemeVersion
//      implements Internal.EnumLite {
//    /**
//     * <pre>
//     * Unsecured - plaintext communication
//     * </pre>
//     *
//     * <code>SecScheme0 = 0;</code>
//     */
//    SecScheme0(0),
//    /**
//     * <pre>
//     * Security scheme 1 - Curve25519 + AES-256-CTR
//     * </pre>
//     *
//     * <code>SecScheme1 = 1;</code>
//     */
//    SecScheme1(1),
//    UNRECOGNIZED(-1),
//    ;
//
//    /**
//     * <pre>
//     * Unsecured - plaintext communication
//     * </pre>
//     *
//     * <code>SecScheme0 = 0;</code>
//     */
//    public static final int SecScheme0_VALUE = 0;
//    /**
//     * <pre>
//     * Security scheme 1 - Curve25519 + AES-256-CTR
//     * </pre>
//     *
//     * <code>SecScheme1 = 1;</code>
//     */
//    public static final int SecScheme1_VALUE = 1;
//
//
//    public final int getNumber() {
//      return value;
//    }
//
//    /**
//     * @deprecated Use {@link #forNumber(int)} instead.
//     */
//    @java.lang.Deprecated
//    public static SecSchemeVersion valueOf(int value) {
//      return forNumber(value);
//    }
//
//    public static SecSchemeVersion forNumber(int value) {
//      switch (value) {
//        case 0: return SecScheme0;
//        case 1: return SecScheme1;
//        default: return null;
//      }
//    }
//
//    public static Internal.EnumLiteMap<SecSchemeVersion>
//        internalGetValueMap() {
//      return internalValueMap;
//    }
//    private static final Internal.EnumLiteMap<
//        SecSchemeVersion> internalValueMap =
//          new Internal.EnumLiteMap<SecSchemeVersion>() {
//            public SecSchemeVersion findValueByNumber(int number) {
//              return SecSchemeVersion.forNumber(number);
//            }
//          };
//
//    private final int value;
//
//    private SecSchemeVersion(int value) {
//      this.value = value;
//    }
//
//    // @@protoc_insertion_point(enum_scope:SecSchemeVersion)
//  }
//
//  public interface SessionDataOrBuilder extends
//      // @@protoc_insertion_point(interface_extends:SessionData)
//      MessageLiteOrBuilder {
//
//    /**
//     * <code>optional .SecSchemeVersion sec_ver = 2;</code>
//     */
//    int getSecVerValue();
//    /**
//     * <code>optional .SecSchemeVersion sec_ver = 2;</code>
//     */
//    Session.SecSchemeVersion getSecVer();
//
//    /**
//     * <code>optional .Sec0Payload sec0 = 10;</code>
//     */
//    Sec0.Sec0Payload getSec0();
//
//    /**
//     * <code>optional .Sec1Payload sec1 = 11;</code>
//     */
//    Sec1.Sec1Payload getSec1();
//
//    public Session.SessionData.ProtoCase getProtoCase();
//  }
//  /**
//   * Protobuf type {@code SessionData}
//   */
//  public  static final class SessionData extends
//      GeneratedMessageLite<
//          SessionData, SessionData.Builder> implements
//      // @@protoc_insertion_point(message_implements:SessionData)
//      SessionDataOrBuilder {
//    private SessionData() {
//    }
//    private int protoCase_ = 0;
//    private java.lang.Object proto_;
//    public enum ProtoCase
//        implements Internal.EnumLite {
//      SEC0(10),
//      SEC1(11),
//      PROTO_NOT_SET(0);
//      private final int value;
//      private ProtoCase(int value) {
//        this.value = value;
//      }
//      /**
//       * @deprecated Use {@link #forNumber(int)} instead.
//       */
//      @java.lang.Deprecated
//      public static ProtoCase valueOf(int value) {
//        return forNumber(value);
//      }
//
//      public static ProtoCase forNumber(int value) {
//        switch (value) {
//          case 10: return SEC0;
//          case 11: return SEC1;
//          case 0: return PROTO_NOT_SET;
//          default: return null;
//        }
//      }
//      public int getNumber() {
//        return this.value;
//      }
//    };
//
//    public ProtoCase
//    getProtoCase() {
//      return ProtoCase.forNumber(
//          protoCase_);
//    }
//
//    private void clearProto() {
//      protoCase_ = 0;
//      proto_ = null;
//    }
//
//    public static final int SEC_VER_FIELD_NUMBER = 2;
//    private int secVer_;
//    /**
//     * <code>optional .SecSchemeVersion sec_ver = 2;</code>
//     */
//    public int getSecVerValue() {
//      return secVer_;
//    }
//    /**
//     * <code>optional .SecSchemeVersion sec_ver = 2;</code>
//     */
//    public Session.SecSchemeVersion getSecVer() {
//      Session.SecSchemeVersion result = Session.SecSchemeVersion.forNumber(secVer_);
//      return result == null ? Session.SecSchemeVersion.UNRECOGNIZED : result;
//    }
//    /**
//     * <code>optional .SecSchemeVersion sec_ver = 2;</code>
//     */
//    private void setSecVerValue(int value) {
//        secVer_ = value;
//    }
//    /**
//     * <code>optional .SecSchemeVersion sec_ver = 2;</code>
//     */
//    private void setSecVer(Session.SecSchemeVersion value) {
//      if (value == null) {
//        throw new NullPointerException();
//      }
//
//      secVer_ = value.getNumber();
//    }
//    /**
//     * <code>optional .SecSchemeVersion sec_ver = 2;</code>
//     */
//    private void clearSecVer() {
//
//      secVer_ = 0;
//    }
//
//    public static final int SEC0_FIELD_NUMBER = 10;
//    /**
//     * <code>optional .Sec0Payload sec0 = 10;</code>
//     */
//    public Sec0.Sec0Payload getSec0() {
//      if (protoCase_ == 10) {
//         return (Sec0.Sec0Payload) proto_;
//      }
//      return Sec0.Sec0Payload.getDefaultInstance();
//    }
//    /**
//     * <code>optional .Sec0Payload sec0 = 10;</code>
//     */
//    private void setSec0(Sec0.Sec0Payload value) {
//      if (value == null) {
//        throw new NullPointerException();
//      }
//      proto_ = value;
//      protoCase_ = 10;
//    }
//    /**
//     * <code>optional .Sec0Payload sec0 = 10;</code>
//     */
//    private void setSec0(
//        Sec0.Sec0Payload.Builder builderForValue) {
//      proto_ = builderForValue.build();
//      protoCase_ = 10;
//    }
//    /**
//     * <code>optional .Sec0Payload sec0 = 10;</code>
//     */
//    private void mergeSec0(Sec0.Sec0Payload value) {
//      if (protoCase_ == 10 &&
//          proto_ != Sec0.Sec0Payload.getDefaultInstance()) {
//        proto_ = Sec0.Sec0Payload.newBuilder((Sec0.Sec0Payload) proto_)
//            .mergeFrom(value).buildPartial();
//      } else {
//        proto_ = value;
//      }
//      protoCase_ = 10;
//    }
//    /**
//     * <code>optional .Sec0Payload sec0 = 10;</code>
//     */
//    private void clearSec0() {
//      if (protoCase_ == 10) {
//        protoCase_ = 0;
//        proto_ = null;
//      }
//    }
//
//    public static final int SEC1_FIELD_NUMBER = 11;
//    /**
//     * <code>optional .Sec1Payload sec1 = 11;</code>
//     */
//    public Sec1.Sec1Payload getSec1() {
//      if (protoCase_ == 11) {
//         return (Sec1.Sec1Payload) proto_;
//      }
//      return Sec1.Sec1Payload.getDefaultInstance();
//    }
//    /**
//     * <code>optional .Sec1Payload sec1 = 11;</code>
//     */
//    private void setSec1(Sec1.Sec1Payload value) {
//      if (value == null) {
//        throw new NullPointerException();
//      }
//      proto_ = value;
//      protoCase_ = 11;
//    }
//    /**
//     * <code>optional .Sec1Payload sec1 = 11;</code>
//     */
//    private void setSec1(
//        Sec1.Sec1Payload.Builder builderForValue) {
//      proto_ = builderForValue.build();
//      protoCase_ = 11;
//    }
//    /**
//     * <code>optional .Sec1Payload sec1 = 11;</code>
//     */
//    private void mergeSec1(Sec1.Sec1Payload value) {
//      if (protoCase_ == 11 &&
//          proto_ != Sec1.Sec1Payload.getDefaultInstance()) {
//        proto_ = Sec1.Sec1Payload.newBuilder((Sec1.Sec1Payload) proto_)
//            .mergeFrom(value).buildPartial();
//      } else {
//        proto_ = value;
//      }
//      protoCase_ = 11;
//    }
//    /**
//     * <code>optional .Sec1Payload sec1 = 11;</code>
//     */
//    private void clearSec1() {
//      if (protoCase_ == 11) {
//        protoCase_ = 0;
//        proto_ = null;
//      }
//    }
//
//    public void writeTo(CodedOutputStream output)
//                        throws java.io.IOException {
//      if (secVer_ != Session.SecSchemeVersion.SecScheme0.getNumber()) {
//        output.writeEnum(2, secVer_);
//      }
//      if (protoCase_ == 10) {
//        output.writeMessage(10, (Sec0.Sec0Payload) proto_);
//      }
//      if (protoCase_ == 11) {
//        output.writeMessage(11, (Sec1.Sec1Payload) proto_);
//      }
//    }
//
//    public int getSerializedSize() {
//      int size = memoizedSerializedSize;
//      if (size != -1) return size;
//
//      size = 0;
//      if (secVer_ != Session.SecSchemeVersion.SecScheme0.getNumber()) {
//        size += CodedOutputStream
//          .computeEnumSize(2, secVer_);
//      }
//      if (protoCase_ == 10) {
//        size += CodedOutputStream
//          .computeMessageSize(10, (Sec0.Sec0Payload) proto_);
//      }
//      if (protoCase_ == 11) {
//        size += CodedOutputStream
//          .computeMessageSize(11, (Sec1.Sec1Payload) proto_);
//      }
//      memoizedSerializedSize = size;
//      return size;
//    }
//
//    public static Session.SessionData parseFrom(
//        ByteString data)
//        throws InvalidProtocolBufferException {
//      return GeneratedMessageLite.parseFrom(
//          DEFAULT_INSTANCE, data);
//    }
//    public static Session.SessionData parseFrom(
//        ByteString data,
//        ExtensionRegistryLite extensionRegistry)
//        throws InvalidProtocolBufferException {
//      return GeneratedMessageLite.parseFrom(
//          DEFAULT_INSTANCE, data, extensionRegistry);
//    }
//    public static Session.SessionData parseFrom(byte[] data)
//        throws InvalidProtocolBufferException {
//      return GeneratedMessageLite.parseFrom(
//          DEFAULT_INSTANCE, data);
//    }
//    public static Session.SessionData parseFrom(
//        byte[] data,
//        ExtensionRegistryLite extensionRegistry)
//        throws InvalidProtocolBufferException {
//      return GeneratedMessageLite.parseFrom(
//          DEFAULT_INSTANCE, data, extensionRegistry);
//    }
//    public static Session.SessionData parseFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return GeneratedMessageLite.parseFrom(
//          DEFAULT_INSTANCE, input);
//    }
//    public static Session.SessionData parseFrom(
//        java.io.InputStream input,
//        ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return GeneratedMessageLite.parseFrom(
//          DEFAULT_INSTANCE, input, extensionRegistry);
//    }
//    public static Session.SessionData parseDelimitedFrom(java.io.InputStream input)
//        throws java.io.IOException {
//      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
//    }
//    public static Session.SessionData parseDelimitedFrom(
//        java.io.InputStream input,
//        ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
//    }
//    public static Session.SessionData parseFrom(
//        CodedInputStream input)
//        throws java.io.IOException {
//      return GeneratedMessageLite.parseFrom(
//          DEFAULT_INSTANCE, input);
//    }
//    public static Session.SessionData parseFrom(
//        CodedInputStream input,
//        ExtensionRegistryLite extensionRegistry)
//        throws java.io.IOException {
//      return GeneratedMessageLite.parseFrom(
//          DEFAULT_INSTANCE, input, extensionRegistry);
//    }
//
//    public static Builder newBuilder() {
//      return DEFAULT_INSTANCE.toBuilder();
//    }
//    public static Builder newBuilder(Session.SessionData prototype) {
//      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
//    }
//
//    /**
//     * Protobuf type {@code SessionData}
//     */
//    public static final class Builder extends
//        GeneratedMessageLite.Builder<
//          Session.SessionData, Builder> implements
//        // @@protoc_insertion_point(builder_implements:SessionData)
//        Session.SessionDataOrBuilder {
//      // Construct using Session.SessionData.newBuilder()
//      private Builder() {
//        super(DEFAULT_INSTANCE);
//      }
//
//      public ProtoCase
//          getProtoCase() {
//        return instance.getProtoCase();
//      }
//
//      public Builder clearProto() {
//        copyOnWrite();
//        instance.clearProto();
//        return this;
//      }
//
//
//      /**
//       * <code>optional .SecSchemeVersion sec_ver = 2;</code>
//       */
//      public int getSecVerValue() {
//        return instance.getSecVerValue();
//      }
//      /**
//       * <code>optional .SecSchemeVersion sec_ver = 2;</code>
//       */
//      public Builder setSecVerValue(int value) {
//        copyOnWrite();
//        instance.setSecVerValue(value);
//        return this;
//      }
//      /**
//       * <code>optional .SecSchemeVersion sec_ver = 2;</code>
//       */
//      public Session.SecSchemeVersion getSecVer() {
//        return instance.getSecVer();
//      }
//      /**
//       * <code>optional .SecSchemeVersion sec_ver = 2;</code>
//       */
//      public Builder setSecVer(Session.SecSchemeVersion value) {
//        copyOnWrite();
//        instance.setSecVer(value);
//        return this;
//      }
//      /**
//       * <code>optional .SecSchemeVersion sec_ver = 2;</code>
//       */
//      public Builder clearSecVer() {
//        copyOnWrite();
//        instance.clearSecVer();
//        return this;
//      }
//
//      /**
//       * <code>optional .Sec0Payload sec0 = 10;</code>
//       */
//      public Sec0.Sec0Payload getSec0() {
//        return instance.getSec0();
//      }
//      /**
//       * <code>optional .Sec0Payload sec0 = 10;</code>
//       */
//      public Builder setSec0(Sec0.Sec0Payload value) {
//        copyOnWrite();
//        instance.setSec0(value);
//        return this;
//      }
//      /**
//       * <code>optional .Sec0Payload sec0 = 10;</code>
//       */
//      public Builder setSec0(
//          Sec0.Sec0Payload.Builder builderForValue) {
//        copyOnWrite();
//        instance.setSec0(builderForValue);
//        return this;
//      }
//      /**
//       * <code>optional .Sec0Payload sec0 = 10;</code>
//       */
//      public Builder mergeSec0(Sec0.Sec0Payload value) {
//        copyOnWrite();
//        instance.mergeSec0(value);
//        return this;
//      }
//      /**
//       * <code>optional .Sec0Payload sec0 = 10;</code>
//       */
//      public Builder clearSec0() {
//        copyOnWrite();
//        instance.clearSec0();
//        return this;
//      }
//
//      /**
//       * <code>optional .Sec1Payload sec1 = 11;</code>
//       */
//      public Sec1.Sec1Payload getSec1() {
//        return instance.getSec1();
//      }
//      /**
//       * <code>optional .Sec1Payload sec1 = 11;</code>
//       */
//      public Builder setSec1(Sec1.Sec1Payload value) {
//        copyOnWrite();
//        instance.setSec1(value);
//        return this;
//      }
//      /**
//       * <code>optional .Sec1Payload sec1 = 11;</code>
//       */
//      public Builder setSec1(
//          Sec1.Sec1Payload.Builder builderForValue) {
//        copyOnWrite();
//        instance.setSec1(builderForValue);
//        return this;
//      }
//      /**
//       * <code>optional .Sec1Payload sec1 = 11;</code>
//       */
//      public Builder mergeSec1(Sec1.Sec1Payload value) {
//        copyOnWrite();
//        instance.mergeSec1(value);
//        return this;
//      }
//      /**
//       * <code>optional .Sec1Payload sec1 = 11;</code>
//       */
//      public Builder clearSec1() {
//        copyOnWrite();
//        instance.clearSec1();
//        return this;
//      }
//
//      // @@protoc_insertion_point(builder_scope:SessionData)
//    }
//    protected final Object dynamicMethod(
//        GeneratedMessageLite.MethodToInvoke method,
//        Object arg0, Object arg1) {
//      switch (method) {
//        case NEW_MUTABLE_INSTANCE: {
//          return new Session.SessionData();
//        }
//        case IS_INITIALIZED: {
//          return DEFAULT_INSTANCE;
//        }
//        case MAKE_IMMUTABLE: {
//          return null;
//        }
//        case NEW_BUILDER: {
//          return new Builder();
//        }
//        case VISIT: {
//          Visitor visitor = (Visitor) arg0;
//          Session.SessionData other = (Session.SessionData) arg1;
//          secVer_ = visitor.visitInt(secVer_ != 0, secVer_,    other.secVer_ != 0, other.secVer_);
//          switch (other.getProtoCase()) {
//            case SEC0: {
//              proto_ = visitor.visitOneofMessage(
//                  protoCase_ == 10,
//                  proto_,
//                  other.proto_);
//              break;
//            }
//            case SEC1: {
//              proto_ = visitor.visitOneofMessage(
//                  protoCase_ == 11,
//                  proto_,
//                  other.proto_);
//              break;
//            }
//            case PROTO_NOT_SET: {
//              visitor.visitOneofNotSet(protoCase_ != 0);
//              break;
//            }
//          }
//          if (visitor == GeneratedMessageLite.MergeFromVisitor
//              .INSTANCE) {
//            if (other.protoCase_ != 0) {
//              protoCase_ = other.protoCase_;
//            }
//          }
//          return this;
//        }
//        case MERGE_FROM_STREAM: {
//          CodedInputStream input =
//              (CodedInputStream) arg0;
//          ExtensionRegistryLite extensionRegistry =
//              (ExtensionRegistryLite) arg1;
//          try {
//            boolean done = false;
//            while (!done) {
//              int tag = input.readTag();
//              switch (tag) {
//                case 0:
//                  done = true;
//                  break;
//                default: {
//                  if (!input.skipField(tag)) {
//                    done = true;
//                  }
//                  break;
//                }
//                case 16: {
//                  int rawValue = input.readEnum();
//
//                  secVer_ = rawValue;
//                  break;
//                }
//                case 82: {
//                  Sec0.Sec0Payload.Builder subBuilder = null;
//                  if (protoCase_ == 10) {
//                    subBuilder = ((Sec0.Sec0Payload) proto_).toBuilder();
//                  }
//                  proto_ =
//                       input.readMessage(Sec0.Sec0Payload.parser(), extensionRegistry);
//                  if (subBuilder != null) {
//                    subBuilder.mergeFrom((Sec0.Sec0Payload) proto_);
//                    proto_ = subBuilder.buildPartial();
//                  }
//                  protoCase_ = 10;
//                  break;
//                }
//                case 90: {
//                  Sec1.Sec1Payload.Builder subBuilder = null;
//                  if (protoCase_ == 11) {
//                    subBuilder = ((Sec1.Sec1Payload) proto_).toBuilder();
//                  }
//                  proto_ =
//                       input.readMessage(Sec1.Sec1Payload.parser(), extensionRegistry);
//                  if (subBuilder != null) {
//                    subBuilder.mergeFrom((Sec1.Sec1Payload) proto_);
//                    proto_ = subBuilder.buildPartial();
//                  }
//                  protoCase_ = 11;
//                  break;
//                }
//              }
//            }
//          } catch (InvalidProtocolBufferException e) {
//            throw new RuntimeException(e.setUnfinishedMessage(this));
//          } catch (java.io.IOException e) {
//            throw new RuntimeException(
//                new InvalidProtocolBufferException(
//                    e.getMessage()).setUnfinishedMessage(this));
//          } finally {
//          }
//        }
//        case GET_DEFAULT_INSTANCE: {
//          return DEFAULT_INSTANCE;
//        }
//        case GET_PARSER: {
//          if (PARSER == null) {    synchronized (Session.SessionData.class) {
//              if (PARSER == null) {
//                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
//              }
//            }
//          }
//          return PARSER;
//        }
//      }
//      throw new UnsupportedOperationException();
//    }
//
//
//    // @@protoc_insertion_point(class_scope:SessionData)
//    private static final Session.SessionData DEFAULT_INSTANCE;
//    static {
//      DEFAULT_INSTANCE = new SessionData();
//      DEFAULT_INSTANCE.makeImmutable();
//    }
//
//    public static Session.SessionData getDefaultInstance() {
//      return DEFAULT_INSTANCE;
//    }
//
//    private static volatile Parser<SessionData> PARSER;
//
//    public static Parser<SessionData> parser() {
//      return DEFAULT_INSTANCE.getParserForType();
//    }
//  }
//
//
//  static {
//  }
//
//  // @@protoc_insertion_point(outer_class_scope)
//}
